import type { Nation } from "../types";

// Groups I–L.
export const PART3: Nation[] = [
  // ─────────────────────────── GROUP I ───────────────────────────
  {
    id: "portugal", name: "Portugal", flag: "🇵🇹", group: "I",
    players: [
      { id: "1", name: "D. Costa", pos: "GK", rating: 84, club: "Porto" },
      { id: "2", name: "J. Sá", pos: "GK", rating: 81, club: "Wolves" },
      { id: "3", name: "J. Cancelo", pos: "RB", alt: ["RWB", "LB"], rating: 83, club: "Al-Hilal" },
      { id: "4", name: "Rúben Dias", pos: "CB", rating: 87, club: "Man City" },
      { id: "5", name: "Pepe", pos: "CB", rating: 78, peak: 86, club: "Free agent" },
      { id: "6", name: "G. Inácio", pos: "CB", alt: ["LB"], rating: 81, club: "Sporting CP" },
      { id: "7", name: "N. Mendes", pos: "LB", alt: ["LWB"], rating: 84, club: "PSG" },
      { id: "8", name: "D. Dalot", pos: "RB", alt: ["RWB", "LB"], rating: 82, club: "Man Utd" },
      { id: "9", name: "R. Neves", pos: "CDM", alt: ["CM"], rating: 84, club: "Al-Hilal" },
      { id: "10", name: "B. Fernandes", pos: "CAM", alt: ["CM", "RW"], rating: 87, club: "Man Utd" },
      { id: "11", name: "Vitinha", pos: "CM", alt: ["CDM", "CAM"], rating: 86, club: "PSG" },
      { id: "12", name: "J. Palhinha", pos: "CDM", rating: 83, club: "Tottenham" },
      { id: "13", name: "J. Neves", pos: "CM", alt: ["CDM"], rating: 82, club: "PSG" },
      { id: "14", name: "B. Silva", pos: "RW", alt: ["CAM", "CM"], rating: 86, club: "Man City" },
      { id: "15", name: "R. Leão", pos: "LW", alt: ["ST"], rating: 85, club: "AC Milan" },
      { id: "16", name: "P. Neto", pos: "RW", alt: ["LW"], rating: 81, club: "Chelsea" },
      { id: "17", name: "F. Conceição", pos: "RW", alt: ["LW"], rating: 80, club: "Juventus" },
      { id: "18", name: "C. Ronaldo", pos: "ST", alt: ["LW"], rating: 84, peak: 94, club: "Al-Nassr" },
      { id: "19", name: "G. Ramos", pos: "ST", rating: 82, club: "PSG" },
      { id: "20", name: "Diogo Jota", pos: "ST", alt: ["LW", "RW"], rating: 83, club: "Liverpool" },
      { id: "21", name: "F. Silva", pos: "ST", alt: ["CF"], rating: 78, club: "RB Leipzig" },
      { id: "22", name: "N. Tavares", pos: "LB", alt: ["LWB"], rating: 79, club: "Lazio" },
    ],
  },
  {
    id: "colombia", name: "Colombia", flag: "🇨🇴", group: "I",
    players: [
      { id: "1", name: "C. Vargas", pos: "GK", rating: 78, club: "Atlético MG" },
      { id: "2", name: "D. Ospina", pos: "GK", rating: 76, peak: 82, club: "Atlético Nacional" },
      { id: "3", name: "D. Muñoz", pos: "RB", alt: ["RWB", "RM"], rating: 81, club: "Crystal Palace" },
      { id: "4", name: "D. Sánchez", pos: "CB", rating: 80, club: "Galatasaray" },
      { id: "5", name: "Y. Mina", pos: "CB", rating: 79, club: "Cagliari" },
      { id: "6", name: "C. Cuesta", pos: "CB", rating: 78, club: "Galatasaray" },
      { id: "7", name: "J. Lucumí", pos: "CB", rating: 79, club: "Bologna" },
      { id: "8", name: "J. Mojica", pos: "LB", alt: ["LWB"], rating: 77, club: "Cagliari" },
      { id: "9", name: "J. Cuadrado", pos: "RM", alt: ["RWB", "RW"], rating: 77, peak: 84, club: "Atlético Nacional" },
      { id: "10", name: "J. Rodríguez", pos: "CAM", alt: ["LW"], rating: 81, peak: 88, club: "Club León" },
      { id: "11", name: "J. Lerma", pos: "CDM", alt: ["CM"], rating: 79, club: "Crystal Palace" },
      { id: "12", name: "R. Ríos", pos: "CM", alt: ["CDM"], rating: 80, club: "Benfica" },
      { id: "13", name: "K. Castaño", pos: "CM", rating: 77, club: "Como" },
      { id: "14", name: "L. Díaz", pos: "LW", alt: ["RW", "ST"], rating: 86, club: "Bayern" },
      { id: "15", name: "L. Sinisterra", pos: "RW", alt: ["LW"], rating: 78, club: "Cruzeiro" },
      { id: "16", name: "J. Arias", pos: "RW", alt: ["CAM"], rating: 78, club: "Wolves" },
      { id: "17", name: "J. Córdoba", pos: "ST", rating: 80, club: "Krasnodar" },
      { id: "18", name: "R. Borré", pos: "ST", alt: ["LW"], rating: 77, club: "Internacional" },
      { id: "19", name: "L. Muriel", pos: "ST", alt: ["CF"], rating: 76, peak: 82, club: "Orlando City" },
      { id: "20", name: "J. Quintero", pos: "CAM", alt: ["CM"], rating: 77, club: "River Plate" },
      { id: "21", name: "D. Valoyes", pos: "RW", rating: 74, club: "Talleres" },
    ],
  },
  {
    id: "iran", name: "Iran", flag: "🇮🇷", group: "I",
    players: [
      { id: "1", name: "A. Beiranvand", pos: "GK", rating: 76, peak: 80, club: "Tractor" },
      { id: "2", name: "P. Niazmand", pos: "GK", rating: 75, club: "Persepolis" },
      { id: "3", name: "S. Moharrami", pos: "RB", alt: ["RWB"], rating: 75, club: "Dinamo Zagreb" },
      { id: "4", name: "M. Hosseini", pos: "CB", rating: 75, club: "Al-Shabab" },
      { id: "5", name: "M. Pouraliganji", pos: "CB", rating: 74, club: "Persepolis" },
      { id: "6", name: "S. Ezatolahi", pos: "CDM", alt: ["CB"], rating: 75, club: "AEK Athens" },
      { id: "7", name: "M. Mohammadi", pos: "LB", alt: ["LWB"], rating: 74, club: "AEK Athens" },
      { id: "8", name: "E. Hajsafi", pos: "LB", alt: ["LM"], rating: 73, peak: 78, club: "AEK Athens" },
      { id: "9", name: "A. Gholizadeh", pos: "LW", alt: ["RW"], rating: 76, club: "Lech Poznań" },
      { id: "10", name: "A. Jahanbakhsh", pos: "RW", alt: ["LW", "CAM"], rating: 77, peak: 80, club: "Heerenveen" },
      { id: "11", name: "S. Ghoddos", pos: "CAM", alt: ["RW"], rating: 76, club: "Brentford" },
      { id: "12", name: "A. Karimi", pos: "CM", alt: ["CDM"], rating: 75, club: "Kuwait SC" },
      { id: "13", name: "A. Noorollahi", pos: "CM", alt: ["CDM"], rating: 74, club: "Persepolis" },
      { id: "14", name: "M. Taremi", pos: "ST", alt: ["RW", "CF"], rating: 81, club: "Inter" },
      { id: "15", name: "S. Azmoun", pos: "ST", rating: 79, peak: 83, club: "Shabab Al-Ahli" },
      { id: "16", name: "K. Ansarifard", pos: "ST", rating: 73, club: "Esteghlal" },
      { id: "17", name: "M. Torabi", pos: "RW", alt: ["LW"], rating: 74, club: "Al-Wakrah" },
      { id: "18", name: "V. Amiri", pos: "CM", rating: 73, club: "Esteghlal" },
      { id: "19", name: "A. Ghaedi", pos: "RW", alt: ["ST"], rating: 74, club: "Esteghlal" },
      { id: "20", name: "O. Noorafkan", pos: "LB", rating: 72, club: "Sepahan" },
      { id: "21", name: "M. Mohebi", pos: "ST", alt: ["RW"], rating: 73, club: "Rostov" },
    ],
  },
  {
    id: "jamaica", name: "Jamaica", flag: "🇯🇲", group: "I",
    players: [
      { id: "1", name: "A. Blake", pos: "GK", rating: 75, club: "Lincoln City" },
      { id: "2", name: "J. Bell", pos: "GK", rating: 72, club: "Harbour View" },
      { id: "3", name: "K. Lawrence", pos: "RB", alt: ["RWB"], rating: 74, club: "Toronto FC" },
      { id: "4", name: "E. King", pos: "CB", rating: 73, club: "FC Cincinnati" },
      { id: "5", name: "D. Bennett", pos: "CB", rating: 73, club: "Free agent" },
      { id: "6", name: "A. Pinnock", pos: "CB", alt: ["LB"], rating: 75, club: "Brentford" },
      { id: "7", name: "D. Lowe", pos: "LB", alt: ["LWB"], rating: 73, club: "Bristol City" },
      { id: "8", name: "K. Palmer", pos: "RB", alt: ["RWB"], rating: 72, club: "Coventry" },
      { id: "9", name: "B. Reid", pos: "CDM", alt: ["CM"], rating: 75, club: "Free agent" },
      { id: "10", name: "K. Hutchinson", pos: "CM", alt: ["CDM"], rating: 73, club: "Sheffield Wed" },
      { id: "11", name: "L. Morrison", pos: "CM", alt: ["CAM"], rating: 74, club: "Atlanta Utd" },
      { id: "12", name: "D. Gray", pos: "RW", alt: ["LW"], rating: 75, peak: 79, club: "Free agent" },
      { id: "13", name: "L. Bailey", pos: "RW", alt: ["LW"], rating: 81, club: "Roma" },
      { id: "14", name: "B. Decordova-Reid", pos: "ST", alt: ["RW", "CAM"], rating: 76, club: "Free agent" },
      { id: "15", name: "S. Nicholson", pos: "LW", alt: ["RW"], rating: 73, club: "Toronto FC" },
      { id: "16", name: "D. Antonio", pos: "ST", rating: 75, peak: 80, club: "West Ham" },
      { id: "17", name: "S. Dacres", pos: "ST", rating: 72, club: "Marítimo" },
      { id: "18", name: "K. Nelson", pos: "ST", rating: 72, club: "Cavalier" },
      { id: "19", name: "T. Latibeaudiere", pos: "CB", rating: 72, club: "Coventry" },
      { id: "20", name: "T. Bartley", pos: "CDM", rating: 71, club: "Mount Pleasant" },
    ],
  },
  // ─────────────────────────── GROUP J ───────────────────────────
  {
    id: "germany", name: "Germany", flag: "🇩🇪", group: "J",
    players: [
      { id: "1", name: "M. ter Stegen", pos: "GK", rating: 86, club: "Barcelona" },
      { id: "2", name: "O. Baumann", pos: "GK", rating: 79, club: "Hoffenheim" },
      { id: "3", name: "J. Kimmich", pos: "RB", alt: ["CDM", "CM"], rating: 87, club: "Bayern" },
      { id: "4", name: "A. Rüdiger", pos: "CB", rating: 86, club: "Real Madrid" },
      { id: "5", name: "J. Tah", pos: "CB", rating: 83, club: "Bayern" },
      { id: "6", name: "N. Schlotterbeck", pos: "CB", alt: ["LB"], rating: 83, club: "Dortmund" },
      { id: "7", name: "W. Anton", pos: "CB", rating: 80, club: "Dortmund" },
      { id: "8", name: "D. Raum", pos: "LB", alt: ["LWB", "LM"], rating: 81, club: "RB Leipzig" },
      { id: "9", name: "R. Andrich", pos: "CDM", alt: ["CM"], rating: 82, club: "Bayer Leverkusen" },
      { id: "10", name: "A. Groß", pos: "CM", alt: ["CDM"], rating: 79, club: "Dortmund" },
      { id: "11", name: "F. Wirtz", pos: "CAM", alt: ["LW", "CM"], rating: 88, club: "Liverpool" },
      { id: "12", name: "J. Musiala", pos: "CAM", alt: ["LW", "RW"], rating: 88, club: "Bayern" },
      { id: "13", name: "P. Groß", pos: "CM", rating: 77, club: "Borussia M." },
      { id: "14", name: "L. Sané", pos: "RW", alt: ["LW"], rating: 84, club: "Galatasaray" },
      { id: "15", name: "S. Gnabry", pos: "RW", alt: ["LW", "ST"], rating: 83, club: "Bayern" },
      { id: "16", name: "K. Adeyemi", pos: "LW", alt: ["RW"], rating: 81, club: "Dortmund" },
      { id: "17", name: "F. Undav", pos: "ST", alt: ["CF"], rating: 80, club: "Stuttgart" },
      { id: "18", name: "N. Füllkrug", pos: "ST", rating: 80, club: "West Ham" },
      { id: "19", name: "K. Havertz", pos: "ST", alt: ["CAM"], rating: 84, club: "Arsenal" },
      { id: "20", name: "J. Gittens", pos: "LW", alt: ["RW"], rating: 79, club: "Chelsea" },
      { id: "21", name: "A. Stiller", pos: "CM", alt: ["CDM"], rating: 79, club: "Stuttgart" },
      { id: "22", name: "R. Gosens", pos: "LWB", alt: ["LB"], rating: 79, club: "Fiorentina" },
    ],
  },
  {
    id: "serbia", name: "Serbia", flag: "🇷🇸", group: "J",
    players: [
      { id: "1", name: "P. Rajković", pos: "GK", rating: 78, club: "Mallorca" },
      { id: "2", name: "Đ. Petrović", pos: "GK", rating: 79, club: "Bournemouth" },
      { id: "3", name: "N. Milenković", pos: "CB", alt: ["RB"], rating: 82, club: "Nottm Forest" },
      { id: "4", name: "S. Pavlović", pos: "CB", alt: ["LB"], rating: 81, club: "Man Utd" },
      { id: "5", name: "M. Veljković", pos: "CB", rating: 78, club: "Werder Bremen" },
      { id: "6", name: "S. Babić", pos: "CB", rating: 76, club: "Red Star" },
      { id: "7", name: "F. Mladenović", pos: "LB", alt: ["LWB"], rating: 75, club: "Panathinaikos" },
      { id: "8", name: "N. Stojković", pos: "RB", alt: ["RWB"], rating: 75, club: "Maccabi TA" },
      { id: "9", name: "S. Milinković-Savić", pos: "CM", alt: ["CAM"], rating: 84, club: "Al-Hilal" },
      { id: "10", name: "N. Gudelj", pos: "CDM", alt: ["CB"], rating: 78, peak: 81, club: "Sevilla" },
      { id: "11", name: "L. Samardžić", pos: "CAM", alt: ["CM", "LW"], rating: 80, club: "Atalanta" },
      { id: "12", name: "I. Ilić", pos: "CM", alt: ["CDM"], rating: 78, club: "Torino" },
      { id: "13", name: "S. Lukić", pos: "CM", alt: ["CDM"], rating: 79, club: "Fulham" },
      { id: "14", name: "A. Živković", pos: "RW", alt: ["LW"], rating: 77, club: "PAOK" },
      { id: "15", name: "F. Kostić", pos: "LWB", alt: ["LW", "LM"], rating: 79, peak: 83, club: "Fenerbahçe" },
      { id: "16", name: "D. Vlahović", pos: "ST", rating: 82, club: "Juventus" },
      { id: "17", name: "A. Mitrović", pos: "ST", rating: 81, peak: 84, club: "Al-Hilal" },
      { id: "18", name: "L. Jović", pos: "ST", alt: ["CF"], rating: 77, club: "AC Milan" },
      { id: "19", name: "N. Maksimović", pos: "CB", rating: 75, club: "Panathinaikos" },
      { id: "20", name: "V. Birmančević", pos: "RW", alt: ["LW"], rating: 76, club: "Sporting CP" },
    ],
  },
  {
    id: "algeria", name: "Algeria", flag: "🇩🇿", group: "J",
    players: [
      { id: "1", name: "A. Oukidja", pos: "GK", rating: 75, club: "FC Metz" },
      { id: "2", name: "L. Zeghba", pos: "GK", rating: 73, club: "CS Constantine" },
      { id: "3", name: "A. Mandi", pos: "CB", alt: ["RB"], rating: 78, club: "Lille" },
      { id: "4", name: "R. Bensebaini", pos: "CB", alt: ["LB"], rating: 80, club: "Dortmund" },
      { id: "5", name: "M. Tougai", pos: "CB", rating: 76, club: "Espérance" },
      { id: "6", name: "Y. Atal", pos: "RB", alt: ["RWB"], rating: 77, peak: 81, club: "Al-Sadd" },
      { id: "7", name: "R. Aït-Nouri", pos: "LB", alt: ["LWB"], rating: 81, club: "Man City" },
      { id: "8", name: "N. Bentaleb", pos: "CM", alt: ["CDM"], rating: 76, peak: 80, club: "Angers" },
      { id: "9", name: "I. Bennacer", pos: "CM", alt: ["CDM"], rating: 81, club: "AC Milan" },
      { id: "10", name: "R. Mahrez", pos: "RW", alt: ["LW"], rating: 84, peak: 87, club: "Al-Ahli" },
      { id: "11", name: "H. Belaïli", pos: "LW", alt: ["RW", "CAM"], rating: 77, club: "Espérance" },
      { id: "12", name: "R. Bentaleb", pos: "CDM", rating: 75, club: "Lille" },
      { id: "13", name: "A. Zerrouki", pos: "CDM", alt: ["CM"], rating: 76, club: "Feyenoord" },
      { id: "14", name: "S. Chaïbi", pos: "CAM", alt: ["RW"], rating: 77, club: "Eintracht" },
      { id: "15", name: "Y. Belaïli", pos: "RW", rating: 75, club: "Espérance" },
      { id: "16", name: "A. Slimani", pos: "ST", rating: 75, peak: 81, club: "Mechelen" },
      { id: "17", name: "B. Bounedjah", pos: "ST", rating: 76, club: "Al-Sadd" },
      { id: "18", name: "M. Amoura", pos: "ST", alt: ["LW", "RW"], rating: 80, club: "Wolfsburg" },
      { id: "19", name: "I. Maza", pos: "CAM", alt: ["CM"], rating: 78, club: "Real Betis" },
      { id: "20", name: "F. Ghoul", pos: "RW", alt: ["LW"], rating: 75, club: "RC Lens" },
    ],
  },
  {
    id: "saudi-arabia", name: "Saudi Arabia", flag: "🇸🇦", group: "J",
    players: [
      { id: "1", name: "N. Al-Owais", pos: "GK", rating: 76, club: "Al-Hilal" },
      { id: "2", name: "M. Al-Rubaie", pos: "GK", rating: 73, club: "Al-Hilal" },
      { id: "3", name: "S. Abdulhamid", pos: "RB", alt: ["RWB"], rating: 75, club: "Al-Hilal" },
      { id: "4", name: "A. Al-Amri", pos: "CB", rating: 74, club: "Al-Nassr" },
      { id: "5", name: "H. Al-Tambakti", pos: "CB", rating: 76, club: "Al-Hilal" },
      { id: "6", name: "A. Al-Bulaihi", pos: "CB", rating: 75, club: "Al-Hilal" },
      { id: "7", name: "Y. Al-Shahrani", pos: "LB", alt: ["LWB"], rating: 75, peak: 78, club: "Al-Hilal" },
      { id: "8", name: "N. Al-Ghannam", pos: "RB", alt: ["RWB"], rating: 73, club: "Al-Nassr" },
      { id: "9", name: "M. Kanno", pos: "CDM", alt: ["CM"], rating: 75, club: "Al-Hilal" },
      { id: "10", name: "S. Al-Dawsari", pos: "LW", alt: ["RW", "CAM"], rating: 80, club: "Al-Hilal" },
      { id: "11", name: "A. Al-Malki", pos: "CM", alt: ["CAM"], rating: 73, club: "Al-Nassr" },
      { id: "12", name: "N. Al-Khaibari", pos: "CM", alt: ["CDM"], rating: 74, club: "Al-Nassr" },
      { id: "13", name: "M. Al-Breik", pos: "RB", rating: 74, club: "Al-Hilal" },
      { id: "14", name: "F. Al-Brikan", pos: "ST", alt: ["CF"], rating: 76, club: "Al-Hilal" },
      { id: "15", name: "A. Al-Hamdan", pos: "ST", rating: 73, club: "Al-Nassr" },
      { id: "16", name: "F. Al-Ghamdi", pos: "RW", alt: ["LW"], rating: 73, club: "Al-Nassr" },
      { id: "17", name: "M. Marran", pos: "CM", rating: 72, club: "Al-Shabab" },
      { id: "18", name: "S. Al-Ghamdi", pos: "RW", alt: ["LW"], rating: 73, club: "Al-Ahli" },
      { id: "19", name: "A. Hazazi", pos: "ST", rating: 72, club: "Al-Ittihad" },
      { id: "20", name: "M. Al-Owais", pos: "CB", rating: 72, club: "Al-Ahli" },
      { id: "21", name: "A. Al-Hassan", pos: "LB", alt: ["LWB"], rating: 72, club: "Al-Ittihad" },
    ],
  },
  // ─────────────────────────── GROUP K ───────────────────────────
  {
    id: "italy", name: "Italy", flag: "🇮🇹", group: "K",
    players: [
      { id: "1", name: "G. Donnarumma", pos: "GK", rating: 88, club: "Man City" },
      { id: "2", name: "G. Vicario", pos: "GK", rating: 82, club: "Tottenham" },
      { id: "3", name: "G. Di Lorenzo", pos: "RB", alt: ["RWB"], rating: 82, club: "Napoli" },
      { id: "4", name: "A. Bastoni", pos: "CB", alt: ["LB"], rating: 85, club: "Inter" },
      { id: "5", name: "R. Calafiori", pos: "CB", alt: ["LB"], rating: 82, club: "Arsenal" },
      { id: "6", name: "A. Buongiorno", pos: "CB", rating: 82, club: "Napoli" },
      { id: "7", name: "F. Dimarco", pos: "LB", alt: ["LWB", "LM"], rating: 84, club: "Inter" },
      { id: "8", name: "G. Cambiaso", pos: "RB", alt: ["LB", "RWB"], rating: 81, club: "Juventus" },
      { id: "9", name: "N. Barella", pos: "CM", alt: ["CDM", "CAM"], rating: 86, club: "Inter" },
      { id: "10", name: "S. Tonali", pos: "CDM", alt: ["CM"], rating: 84, club: "Newcastle" },
      { id: "11", name: "D. Frattesi", pos: "CM", alt: ["CAM"], rating: 80, club: "Inter" },
      { id: "12", name: "M. Locatelli", pos: "CDM", alt: ["CM"], rating: 80, club: "Juventus" },
      { id: "13", name: "L. Pellegrini", pos: "CAM", alt: ["CM"], rating: 79, peak: 83, club: "Roma" },
      { id: "14", name: "F. Chiesa", pos: "RW", alt: ["LW", "ST"], rating: 81, club: "Liverpool" },
      { id: "15", name: "N. Zaniolo", pos: "RW", alt: ["CAM", "ST"], rating: 77, club: "Udinese" },
      { id: "16", name: "M. Politano", pos: "RM", alt: ["RW"], rating: 79, club: "Napoli" },
      { id: "17", name: "G. Scamacca", pos: "ST", rating: 80, club: "Atalanta" },
      { id: "18", name: "M. Retegui", pos: "ST", rating: 82, club: "Al-Qadsiah" },
      { id: "19", name: "M. Kean", pos: "ST", alt: ["CF"], rating: 81, club: "Fiorentina" },
      { id: "20", name: "G. Raspadori", pos: "CF", alt: ["ST", "LW"], rating: 78, club: "Atlético" },
      { id: "21", name: "A. Cambiaghi", pos: "LW", alt: ["RW"], rating: 76, club: "Bologna" },
      { id: "22", name: "S. Esposito", pos: "ST", alt: ["CF"], rating: 76, club: "Cagliari" },
    ],
  },
  {
    id: "turkey", name: "Turkey", flag: "🇹🇷", group: "K",
    players: [
      { id: "1", name: "U. Çakır", pos: "GK", rating: 80, club: "Galatasaray" },
      { id: "2", name: "A. Bayındır", pos: "GK", rating: 78, club: "Man Utd" },
      { id: "3", name: "Z. Çelik", pos: "RB", alt: ["RWB"], rating: 78, club: "Inter" },
      { id: "4", name: "M. Demiral", pos: "CB", rating: 81, club: "Al-Ahli" },
      { id: "5", name: "M. Akaydın", pos: "CB", rating: 77, club: "Fenerbahçe" },
      { id: "6", name: "S. Bardakcı", pos: "CB", rating: 78, club: "Galatasaray" },
      { id: "7", name: "F. Kadıoğlu", pos: "LB", alt: ["LWB", "LM"], rating: 80, club: "Inter" },
      { id: "8", name: "A. Müldür", pos: "RB", alt: ["RWB"], rating: 77, club: "Fenerbahçe" },
      { id: "9", name: "H. Çalhanoğlu", pos: "CDM", alt: ["CM", "CAM"], rating: 86, club: "Inter" },
      { id: "10", name: "İ. Yüksek", pos: "CDM", alt: ["CM"], rating: 78, club: "Fenerbahçe" },
      { id: "11", name: "S. Özcan", pos: "CDM", alt: ["CM"], rating: 79, club: "Dortmund" },
      { id: "12", name: "A. Güler", pos: "CAM", alt: ["CM", "RW"], rating: 83, club: "Real Madrid" },
      { id: "13", name: "O. Kahveci", pos: "CAM", alt: ["RW"], rating: 77, club: "Fenerbahçe" },
      { id: "14", name: "K. Aktürkoğlu", pos: "LW", alt: ["RW"], rating: 80, club: "Benfica" },
      { id: "15", name: "K. Akgün", pos: "RW", alt: ["LW"], rating: 79, club: "Galatasaray" },
      { id: "16", name: "C. Ünder", pos: "RW", alt: ["LW"], rating: 77, peak: 81, club: "Fenerbahçe" },
      { id: "17", name: "B. Yılmaz", pos: "ST", rating: 80, club: "Galatasaray" },
      { id: "18", name: "S. Tekdemir", pos: "CDM", rating: 75, club: "Antalyaspor" },
      { id: "19", name: "Y. Akçiçek", pos: "CB", alt: ["RB"], rating: 76, club: "Fenerbahçe" },
      { id: "20", name: "E. Dervişoğlu", pos: "ST", rating: 75, club: "Gaziantep" },
    ],
  },
  {
    id: "ghana", name: "Ghana", flag: "🇬🇭", group: "K",
    players: [
      { id: "1", name: "L. Nurudeen", pos: "GK", rating: 74, club: "Asante Kotoko" },
      { id: "2", name: "B. Ati-Zigi", pos: "GK", rating: 75, club: "St. Gallen" },
      { id: "3", name: "T. Lamptey", pos: "RB", alt: ["RWB", "RM"], rating: 77, club: "Brighton" },
      { id: "4", name: "M. Salisu", pos: "CB", rating: 78, club: "Monaco" },
      { id: "5", name: "A. Djiku", pos: "CB", rating: 77, club: "Fenerbahçe" },
      { id: "6", name: "A. Seidu", pos: "RB", alt: ["RWB", "CB"], rating: 74, club: "RC Lens" },
      { id: "7", name: "G. Mensah", pos: "LB", alt: ["LWB"], rating: 75, club: "Salernitana" },
      { id: "8", name: "T. Partey", pos: "CDM", alt: ["CM", "CB"], rating: 83, club: "Villarreal" },
      { id: "9", name: "M. Kudus", pos: "RW", alt: ["CAM", "LW"], rating: 83, club: "Tottenham" },
      { id: "10", name: "E. Lamptey", pos: "CM", alt: ["CDM"], rating: 75, club: "Almería" },
      { id: "11", name: "S. Owusu", pos: "CM", alt: ["CDM"], rating: 75, club: "Fortuna Sittard" },
      { id: "12", name: "M. Sulemana", pos: "LW", alt: ["RW"], rating: 79, club: "Atalanta" },
      { id: "13", name: "E. Nuamah", pos: "LW", alt: ["RW", "ST"], rating: 78, club: "Lyon" },
      { id: "14", name: "A. Semenyo", pos: "RW", alt: ["ST", "LW"], rating: 80, club: "Bournemouth" },
      { id: "15", name: "J. Ayew", pos: "ST", alt: ["RW", "CAM"], rating: 75, peak: 80, club: "Free agent" },
      { id: "16", name: "I. Williams", pos: "ST", alt: ["RW"], rating: 78, club: "Athletic Club" },
      { id: "17", name: "K. Fosu-Mensah", pos: "RB", alt: ["CB"], rating: 73, club: "Antwerp" },
      { id: "18", name: "B. Brobbey", pos: "ST", rating: 76, club: "Ajax" },
      { id: "19", name: "F. Aidoo", pos: "CB", rating: 73, club: "Celtic" },
      { id: "20", name: "K. Sowah", pos: "CM", alt: ["CAM"], rating: 73, club: "Charlotte FC" },
    ],
  },
  {
    id: "uzbekistan", name: "Uzbekistan", flag: "🇺🇿", group: "K",
    players: [
      { id: "1", name: "U. Eshmuradov", pos: "GK", rating: 73, club: "Pakhtakor" },
      { id: "2", name: "A. Yusupov", pos: "GK", rating: 72, club: "Nasaf" },
      { id: "3", name: "A. Khamdamov", pos: "RB", alt: ["RWB"], rating: 73, club: "Pakhtakor" },
      { id: "4", name: "R. Khusanov", pos: "CB", alt: ["RB"], rating: 79, club: "Man City" },
      { id: "5", name: "A. Khoshimov", pos: "CB", rating: 73, club: "Pakhtakor" },
      { id: "6", name: "U. Eshmuminov", pos: "CB", rating: 73, club: "Pakhtakor" },
      { id: "7", name: "A. Sa'dullaev", pos: "LB", alt: ["LWB"], rating: 73, club: "Pakhtakor" },
      { id: "8", name: "J. Iskanderov", pos: "CM", alt: ["CAM"], rating: 75, club: "Pakhtakor" },
      { id: "9", name: "A. Urunov", pos: "CAM", alt: ["RW"], rating: 75, club: "Rubin Kazan" },
      { id: "10", name: "O. Zoirov", pos: "CDM", alt: ["CM"], rating: 73, club: "Nasaf" },
      { id: "11", name: "J. Masharipov", pos: "LW", alt: ["CAM", "RW"], rating: 76, club: "Pakhtakor" },
      { id: "12", name: "I. Tukhtakhujaev", pos: "CM", rating: 72, club: "Pakhtakor" },
      { id: "13", name: "K. Turaev", pos: "CM", alt: ["CDM"], rating: 73, club: "Nasaf" },
      { id: "14", name: "O. Hamrobekov", pos: "CDM", rating: 73, club: "Pakhtakor" },
      { id: "15", name: "E. Shomurodov", pos: "ST", rating: 78, club: "Roma" },
      { id: "16", name: "I. Nazarov", pos: "RW", alt: ["LW"], rating: 73, club: "Navbahor" },
      { id: "17", name: "K. Shukurov", pos: "RM", alt: ["RW"], rating: 72, club: "AGMK" },
      { id: "18", name: "A. Fayzullaev", pos: "CAM", alt: ["LW", "RW"], rating: 77, club: "CSKA Moscow" },
      { id: "19", name: "S. Yakhshiboev", pos: "ST", alt: ["RW"], rating: 73, club: "Ludogorets" },
      { id: "20", name: "B. Tursunov", pos: "RW", alt: ["LW"], rating: 73, club: "Spartak Moscow" },
      { id: "21", name: "O. Bo'riyev", pos: "ST", rating: 72, club: "Pakhtakor" },
    ],
  },
  // ─────────────────────────── GROUP L ───────────────────────────
  {
    id: "austria", name: "Austria", flag: "🇦🇹", group: "L",
    players: [
      { id: "1", name: "P. Pentz", pos: "GK", rating: 77, club: "Stade Brestois" },
      { id: "2", name: "N. Hedl", pos: "GK", rating: 74, club: "Rapid Wien" },
      { id: "3", name: "S. Posch", pos: "RB", alt: ["CB", "RWB"], rating: 78, club: "Bologna" },
      { id: "4", name: "K. Danso", pos: "CB", rating: 79, club: "Tottenham" },
      { id: "5", name: "P. Lienhart", pos: "CB", rating: 78, club: "Freiburg" },
      { id: "6", name: "M. Wöber", pos: "CB", alt: ["LB"], rating: 77, club: "Borussia M." },
      { id: "7", name: "P. Mwene", pos: "LB", alt: ["LWB", "RB"], rating: 76, club: "Mainz" },
      { id: "8", name: "A. Schlager", pos: "CDM", alt: ["CM"], rating: 80, club: "RB Leipzig" },
      { id: "9", name: "N. Seiwald", pos: "CDM", alt: ["CM"], rating: 79, club: "RB Leipzig" },
      { id: "10", name: "K. Laimer", pos: "CM", alt: ["RB", "CDM"], rating: 81, club: "Bayern" },
      { id: "11", name: "C. Baumgartner", pos: "CAM", alt: ["CM"], rating: 81, club: "RB Leipzig" },
      { id: "12", name: "R. Sabitzer", pos: "CM", alt: ["CAM"], rating: 81, club: "Dortmund" },
      { id: "13", name: "M. Sabitzer", pos: "CM", rating: 75, club: "LASK" },
      { id: "14", name: "P. Wimmer", pos: "LW", alt: ["RW"], rating: 78, club: "Wolfsburg" },
      { id: "15", name: "M. Gregoritsch", pos: "ST", alt: ["CF"], rating: 78, club: "Freiburg" },
      { id: "16", name: "M. Arnautović", pos: "ST", rating: 77, peak: 83, club: "Inter" },
      { id: "17", name: "P. Baumgartner", pos: "CAM", alt: ["RW"], rating: 76, club: "Hoffenheim" },
      { id: "18", name: "R. Grüll", pos: "LW", alt: ["RW", "ST"], rating: 76, club: "Werder Bremen" },
      { id: "19", name: "M. Entrup", pos: "ST", rating: 74, club: "Rapid Wien" },
      { id: "20", name: "A. Prass", pos: "LWB", alt: ["LM", "LB"], rating: 76, club: "Sturm Graz" },
    ],
  },
  {
    id: "south-korea", name: "South Korea", flag: "🇰🇷", group: "L",
    players: [
      { id: "1", name: "Kim S.", pos: "GK", rating: 78, club: "Mainz" },
      { id: "2", name: "Jo H.", pos: "GK", rating: 75, club: "Ulsan HD" },
      { id: "3", name: "Kim M.", pos: "RB", alt: ["RWB"], rating: 75, club: "FC Seoul" },
      { id: "4", name: "Kim M.-j.", pos: "CB", rating: 86, club: "Bayern" },
      { id: "5", name: "Kim Y.-g.", pos: "CB", rating: 76, club: "Ulsan HD" },
      { id: "6", name: "Jung S.-b.", pos: "CB", alt: ["LB"], rating: 75, club: "FC Seoul" },
      { id: "7", name: "Kim J.-s.", pos: "LB", alt: ["LWB"], rating: 76, club: "Mainz" },
      { id: "8", name: "Lee K.-i.", pos: "CDM", alt: ["CM"], rating: 77, club: "FC Seoul" },
      { id: "9", name: "Hwang I.-b.", pos: "CDM", alt: ["CM"], rating: 76, club: "Feyenoord" },
      { id: "10", name: "Lee J.-s.", pos: "CM", alt: ["CDM"], rating: 79, club: "PSG" },
      { id: "11", name: "Hong H.-c.", pos: "CM", alt: ["RB"], rating: 76, club: "Nottm Forest" },
      { id: "12", name: "Park Y.-w.", pos: "CM", alt: ["CAM"], rating: 75, club: "Gimcheon Sangmu" },
      { id: "13", name: "Son H.-m.", pos: "LW", alt: ["ST", "RW"], rating: 85, peak: 89, club: "LAFC" },
      { id: "14", name: "Lee K.-j.", pos: "RW", alt: ["LW"], rating: 76, club: "FC Seoul" },
      { id: "15", name: "Hwang H.-c.", pos: "RW", alt: ["LW"], rating: 79, club: "Wolves" },
      { id: "16", name: "Hwang U.-j.", pos: "RM", alt: ["RW"], rating: 75, club: "Suwon FC" },
      { id: "17", name: "Oh H.-g.", pos: "ST", rating: 79, club: "Marseille" },
      { id: "18", name: "Cho G.-s.", pos: "ST", rating: 78, club: "Midtjylland" },
      { id: "19", name: "Joo M.-g.", pos: "CAM", alt: ["RW"], rating: 75, club: "FC Seoul" },
      { id: "20", name: "Bae J.-h.", pos: "RB", alt: ["RWB"], rating: 75, club: "Salernitana" },
    ],
  },
  {
    id: "cameroon", name: "Cameroon", flag: "🇨🇲", group: "L",
    players: [
      { id: "1", name: "A. Onana", pos: "GK", rating: 82, club: "Trabzonspor" },
      { id: "2", name: "D. Epassy", pos: "GK", rating: 73, club: "Abha" },
      { id: "3", name: "C. Tolo", pos: "LB", alt: ["LWB"], rating: 74, club: "Hoffenheim" },
      { id: "4", name: "N. Ngadeu", pos: "CB", rating: 76, club: "Sint-Truiden" },
      { id: "5", name: "C. Wooh", pos: "CB", rating: 77, club: "Rennes" },
      { id: "6", name: "J.-C. Castelletto", pos: "CB", rating: 75, club: "FC Nantes" },
      { id: "7", name: "E. Mbeumo", pos: "RW", alt: ["ST", "LW"], rating: 83, club: "Man Utd" },
      { id: "8", name: "O. Ntcham", pos: "CM", alt: ["CDM"], rating: 74, club: "Samsunspor" },
      { id: "9", name: "A. Anguissa", pos: "CM", alt: ["CDM"], rating: 84, club: "Napoli" },
      { id: "10", name: "M. Hongla", pos: "CDM", alt: ["CM"], rating: 74, club: "Hellas Verona" },
      { id: "11", name: "C. Baleba", pos: "CDM", alt: ["CM"], rating: 81, club: "Brighton" },
      { id: "12", name: "G. Choupo-Moting", pos: "ST", alt: ["CF"], rating: 76, peak: 82, club: "Sunderland" },
      { id: "13", name: "B. Magri", pos: "RW", alt: ["LW"], rating: 74, club: "Toulouse" },
      { id: "14", name: "K. Toko Ekambi", pos: "LW", alt: ["ST"], rating: 76, peak: 81, club: "Abha" },
      { id: "15", name: "V. Aboubakar", pos: "ST", rating: 76, peak: 81, club: "Hatayspor" },
      { id: "16", name: "F. Mbella", pos: "ST", rating: 73, club: "Young Boys" },
      { id: "17", name: "N. Moumi Ngamaleu", pos: "RW", alt: ["LW"], rating: 75, club: "Dynamo Moscow" },
      { id: "18", name: "M. Wooh", pos: "RB", alt: ["RWB"], rating: 73, club: "Lens" },
      { id: "19", name: "C. Oyongo", pos: "LB", alt: ["LWB"], rating: 73, club: "Montpellier" },
      { id: "20", name: "F. Anguissa", pos: "CM", rating: 73, club: "Coton Sport" },
    ],
  },
  {
    id: "dr-congo", name: "DR Congo", flag: "🇨🇩", group: "L",
    players: [
      { id: "1", name: "L. Mpasi", pos: "GK", rating: 74, club: "Amiens" },
      { id: "2", name: "T. Kialonda", pos: "GK", rating: 72, club: "Free agent" },
      { id: "3", name: "A. Masuaku", pos: "LB", alt: ["LWB", "LM"], rating: 76, club: "Sunderland" },
      { id: "4", name: "C. Mbemba", pos: "CB", alt: ["CDM"], rating: 80, club: "LOSC Lille" },
      { id: "5", name: "G. Kasanga", pos: "CB", rating: 74, club: "RC Lens" },
      { id: "6", name: "D. Mukoko", pos: "CB", rating: 73, club: "Free agent" },
      { id: "7", name: "R. Pickel", pos: "RB", alt: ["RWB", "CM"], rating: 75, club: "Cremonese" },
      { id: "8", name: "S. Moutoussamy", pos: "CDM", alt: ["CM"], rating: 76, club: "Udinese" },
      { id: "9", name: "E. Wissa", pos: "ST", alt: ["LW"], rating: 81, club: "Newcastle" },
      { id: "10", name: "C. Bakambu", pos: "ST", rating: 76, peak: 80, club: "Real Betis" },
      { id: "11", name: "T. Mbuku", pos: "RW", alt: ["LW"], rating: 75, club: "RC Lens" },
      { id: "12", name: "Y. Wan-Bissaka", pos: "RB", alt: ["RWB"], rating: 80, club: "West Ham" },
      { id: "13", name: "N. Bakambu", pos: "CM", rating: 73, club: "Free agent" },
      { id: "14", name: "M. Bongonda", pos: "LW", alt: ["RW"], rating: 76, club: "Spartak Moscow" },
      { id: "15", name: "S. Mayele", pos: "ST", alt: ["RW"], rating: 76, club: "Pyramids" },
      { id: "16", name: "G. Kakuta", pos: "CAM", alt: ["LW"], rating: 75, peak: 79, club: "Amiens" },
      { id: "17", name: "N. Elia", pos: "RW", alt: ["LW"], rating: 73, club: "Salzburg" },
      { id: "18", name: "B. Mpasi", pos: "CM", alt: ["CDM"], rating: 73, club: "Free agent" },
      { id: "19", name: "C. Mukau", pos: "CM", alt: ["CDM"], rating: 75, club: "FC Augsburg" },
      { id: "20", name: "M. Kayembe", pos: "RB", alt: ["CB"], rating: 73, club: "Anderlecht" },
    ],
  },
];
