import type { Nation } from "../types";

// Groups E–H.
export const PART2: Nation[] = [
  // ─────────────────────────── GROUP E ───────────────────────────
  {
    id: "france", name: "France", flag: "🇫🇷", group: "E",
    players: [
      { id: "1", name: "M. Maignan", pos: "GK", rating: 85, club: "AC Milan" },
      { id: "2", name: "B. Samba", pos: "GK", rating: 80, club: "Rennes" },
      { id: "3", name: "J. Koundé", pos: "RB", alt: ["CB", "RWB"], rating: 84, club: "Barcelona" },
      { id: "4", name: "D. Upamecano", pos: "CB", rating: 85, club: "Bayern" },
      { id: "5", name: "W. Saliba", pos: "CB", rating: 86, club: "Arsenal" },
      { id: "6", name: "I. Konaté", pos: "CB", rating: 84, club: "Liverpool" },
      { id: "7", name: "T. Hernández", pos: "LB", alt: ["LWB"], rating: 84, club: "Como" },
      { id: "8", name: "L. Hernández", pos: "LB", alt: ["CB"], rating: 81, club: "PSG" },
      { id: "9", name: "A. Tchouaméni", pos: "CDM", alt: ["CB", "CM"], rating: 86, club: "Real Madrid" },
      { id: "10", name: "E. Camavinga", pos: "CM", alt: ["CDM", "LB"], rating: 85, club: "Real Madrid" },
      { id: "11", name: "A. Rabiot", pos: "CM", alt: ["CDM"], rating: 83, club: "AC Milan" },
      { id: "12", name: "W. Zaïre-Emery", pos: "CM", alt: ["CDM"], rating: 81, club: "PSG" },
      { id: "13", name: "K. Mbappé", pos: "ST", alt: ["LW", "CF"], rating: 91, club: "Real Madrid" },
      { id: "14", name: "O. Dembélé", pos: "RW", alt: ["LW", "ST"], rating: 88, club: "PSG" },
      { id: "15", name: "M. Olise", pos: "RW", alt: ["CAM"], rating: 85, club: "Bayern" },
      { id: "16", name: "B. Barcola", pos: "LW", alt: ["RW"], rating: 83, club: "PSG" },
      { id: "17", name: "K. Thuram", pos: "CM", alt: ["CDM"], rating: 82, club: "Juventus" },
      { id: "18", name: "M. Thuram", pos: "ST", alt: ["CF"], rating: 84, club: "Inter" },
      { id: "19", name: "R. Kolo Muani", pos: "ST", rating: 81, club: "Juventus" },
      { id: "20", name: "B. Doué", pos: "RW", alt: ["CAM", "LW"], rating: 81, club: "PSG" },
      { id: "21", name: "J. Clauss", pos: "RWB", alt: ["RB"], rating: 79, club: "Nice" },
      { id: "22", name: "L. Digne", pos: "LB", alt: ["LWB"], rating: 79, club: "Aston Villa" },
    ],
  },
  {
    id: "senegal", name: "Senegal", flag: "🇸🇳", group: "E",
    players: [
      { id: "1", name: "É. Mendy", pos: "GK", rating: 81, peak: 85, club: "Al-Ahli" },
      { id: "2", name: "M. Diaw", pos: "GK", rating: 74, club: "Damac" },
      { id: "3", name: "K. Koulibaly", pos: "CB", rating: 82, peak: 87, club: "Al-Hilal" },
      { id: "4", name: "A. Diallo", pos: "CB", alt: ["LB"], rating: 81, club: "Al-Arabi" },
      { id: "5", name: "M. Niakhaté", pos: "CB", rating: 79, club: "Lyon" },
      { id: "6", name: "I. Jakobs", pos: "LB", alt: ["LWB"], rating: 78, club: "Al-Nassr" },
      { id: "7", name: "F. Mendy", pos: "RB", alt: ["RWB"], rating: 76, club: "Reims" },
      { id: "8", name: "A. Mendy", pos: "CB", rating: 76, club: "Lens" },
      { id: "9", name: "I. Gueye", pos: "CDM", alt: ["CM"], rating: 80, peak: 83, club: "Everton" },
      { id: "10", name: "P. Sarr", pos: "CM", alt: ["CDM"], rating: 81, club: "Tottenham" },
      { id: "11", name: "P. Gueye", pos: "CDM", alt: ["CM"], rating: 78, club: "Marseille" },
      { id: "12", name: "L. Camara", pos: "CM", alt: ["CAM"], rating: 78, club: "Monaco" },
      { id: "13", name: "S. Mané", pos: "LW", alt: ["RW", "ST"], rating: 83, peak: 90, club: "Al-Nassr" },
      { id: "14", name: "I. Sarr", pos: "RW", alt: ["LW"], rating: 82, club: "Crystal Palace" },
      { id: "15", name: "N. Jackson", pos: "ST", alt: ["LW"], rating: 80, club: "Bayern" },
      { id: "16", name: "B. Dia", pos: "ST", alt: ["RW"], rating: 78, club: "Lazio" },
      { id: "17", name: "H. Diallo", pos: "ST", rating: 77, club: "Al-Duhail" },
      { id: "18", name: "C. Ndiaye", pos: "RW", alt: ["LW"], rating: 79, club: "Everton" },
      { id: "19", name: "P. Ciss", pos: "CDM", alt: ["RB"], rating: 76, club: "Al-Ettifaq" },
      { id: "20", name: "F. Diédhiou", pos: "ST", rating: 75, club: "Grenoble" },
      { id: "21", name: "A. Diarra", pos: "CM", rating: 75, club: "FC Metz" },
    ],
  },
  {
    id: "poland", name: "Poland", flag: "🇵🇱", group: "E",
    players: [
      { id: "1", name: "Ł. Skorupski", pos: "GK", rating: 79, club: "Bologna" },
      { id: "2", name: "M. Bułka", pos: "GK", rating: 77, club: "Nice" },
      { id: "3", name: "J. Bednarek", pos: "CB", rating: 79, club: "Porto" },
      { id: "4", name: "J. Kiwior", pos: "CB", alt: ["LB"], rating: 80, club: "Porto" },
      { id: "5", name: "P. Bereszyński", pos: "RB", alt: ["RWB", "CB"], rating: 76, club: "Empoli" },
      { id: "6", name: "B. Cash", pos: "RB", alt: ["RWB"], rating: 77, club: "Aston Villa" },
      { id: "7", name: "P. Zalewski", pos: "LB", alt: ["LWB", "LM"], rating: 78, club: "Atalanta" },
      { id: "8", name: "T. Kędziora", pos: "RB", rating: 74, club: "Hajduk Split" },
      { id: "9", name: "P. Zieliński", pos: "CAM", alt: ["CM"], rating: 83, club: "Inter" },
      { id: "10", name: "S. Szymański", pos: "CAM", alt: ["RM"], rating: 79, club: "Fenerbahçe" },
      { id: "11", name: "N. Zalewski", pos: "LM", alt: ["LW"], rating: 77, club: "Inter" },
      { id: "12", name: "J. Moder", pos: "CM", alt: ["CDM"], rating: 78, club: "Feyenoord" },
      { id: "13", name: "B. Slisz", pos: "CDM", alt: ["CM"], rating: 76, club: "Atlanta Utd" },
      { id: "14", name: "K. Pióro", pos: "CM", rating: 73, club: "Legia Warsaw" },
      { id: "15", name: "M. Frankowski", pos: "RM", alt: ["RW"], rating: 77, club: "Lens" },
      { id: "16", name: "K. Świderski", pos: "ST", alt: ["LW"], rating: 77, club: "Panathinaikos" },
      { id: "17", name: "R. Lewandowski", pos: "ST", rating: 87, peak: 91, club: "Barcelona" },
      { id: "18", name: "A. Buksa", pos: "ST", rating: 76, club: "Midtjylland" },
      { id: "19", name: "K. Piątek", pos: "ST", rating: 76, peak: 81, club: "Al-Duhail" },
      { id: "20", name: "N. Iwański", pos: "RW", alt: ["LW"], rating: 73, club: "Legia Warsaw" },
    ],
  },
  {
    id: "new-zealand", name: "New Zealand", flag: "🇳🇿", group: "E",
    players: [
      { id: "1", name: "M. Crocombe", pos: "GK", rating: 72, club: "Wellington Phoenix" },
      { id: "2", name: "A. Paulsen", pos: "GK", rating: 73, club: "Aberdeen" },
      { id: "3", name: "T. Payne", pos: "RB", alt: ["RWB"], rating: 72, club: "Wellington Phoenix" },
      { id: "4", name: "M. Boxall", pos: "CB", rating: 73, club: "Minnesota Utd" },
      { id: "5", name: "N. Tuanga", pos: "CB", rating: 71, club: "AS Saint-Étienne" },
      { id: "6", name: "F. Bell", pos: "CB", rating: 71, club: "Hearts" },
      { id: "7", name: "L. Cacace", pos: "LB", alt: ["LWB", "LM"], rating: 73, club: "Empoli" },
      { id: "8", name: "J. Bell", pos: "RB", rating: 71, club: "Salford City" },
      { id: "9", name: "J. Stamenić", pos: "CDM", alt: ["CM"], rating: 73, club: "Hajduk Split" },
      { id: "10", name: "M. Garbett", pos: "CM", alt: ["CAM"], rating: 73, club: "Estoril" },
      { id: "11", name: "C. Wood", pos: "ST", rating: 79, club: "Nottm Forest" },
      { id: "12", name: "B. Old", pos: "CM", rating: 72, club: "Auckland FC" },
      { id: "13", name: "A. Barbarouses", pos: "RW", alt: ["LW"], rating: 72, club: "Auckland FC" },
      { id: "14", name: "E. Just", pos: "LW", alt: ["RW"], rating: 71, club: "Randers FC" },
      { id: "15", name: "B. Waine", pos: "ST", rating: 72, club: "Shrewsbury" },
      { id: "16", name: "K. Surman", pos: "CM", rating: 70, club: "Western Sydney" },
      { id: "17", name: "M. Steinmann", pos: "CM", alt: ["CAM"], rating: 71, club: "Grasshopper" },
      { id: "18", name: "S. van der Hoorn", pos: "LB", rating: 70, club: "Auckland FC" },
      { id: "19", name: "O. Whyte", pos: "RW", alt: ["ST"], rating: 71, club: "Charlton" },
      { id: "20", name: "F. Talbot", pos: "ST", rating: 70, club: "Wellington Phoenix" },
      { id: "21", name: "D. Singh", pos: "RW", alt: ["LW"], rating: 70, club: "Auckland FC" },
    ],
  },
  // ─────────────────────────── GROUP F ───────────────────────────
  {
    id: "argentina", name: "Argentina", flag: "🇦🇷", group: "F",
    players: [
      { id: "1", name: "E. Martínez", pos: "GK", rating: 86, club: "Aston Villa" },
      { id: "2", name: "G. Rulli", pos: "GK", rating: 79, club: "Marseille" },
      { id: "3", name: "N. Molina", pos: "RB", alt: ["RWB"], rating: 80, club: "Atlético" },
      { id: "4", name: "C. Romero", pos: "CB", rating: 85, club: "Tottenham" },
      { id: "5", name: "L. Martínez", pos: "CB", alt: ["LB"], rating: 84, club: "Atlético" },
      { id: "6", name: "N. Otamendi", pos: "CB", rating: 80, peak: 84, club: "Benfica" },
      { id: "7", name: "N. Tagliafico", pos: "LB", alt: ["LWB"], rating: 80, club: "Lyon" },
      { id: "8", name: "M. Acuña", pos: "LB", alt: ["LWB", "LM"], rating: 79, club: "River Plate" },
      { id: "9", name: "R. De Paul", pos: "CM", alt: ["CDM"], rating: 84, club: "Inter MIA" },
      { id: "10", name: "E. Fernández", pos: "CM", alt: ["CDM"], rating: 84, club: "Chelsea" },
      { id: "11", name: "A. Mac Allister", pos: "CM", alt: ["CAM"], rating: 86, club: "Liverpool" },
      { id: "12", name: "L. Paredes", pos: "CDM", alt: ["CM"], rating: 80, club: "Boca Juniors" },
      { id: "13", name: "G. Lo Celso", pos: "CAM", alt: ["CM"], rating: 80, club: "Real Betis" },
      { id: "14", name: "L. Messi", pos: "RW", alt: ["CAM", "CF"], rating: 88, peak: 94, club: "Inter MIA" },
      { id: "15", name: "Á. Di María", pos: "RW", alt: ["LW"], rating: 81, peak: 87, club: "Rosario Central" },
      { id: "16", name: "J. Álvarez", pos: "ST", alt: ["CF", "RW"], rating: 86, club: "Atlético" },
      { id: "17", name: "L. Martínez", pos: "ST", rating: 87, club: "Inter" },
      { id: "18", name: "N. González", pos: "LW", alt: ["RW"], rating: 81, club: "Juventus" },
      { id: "19", name: "G. Garnacho", pos: "LW", alt: ["RW"], rating: 80, club: "Chelsea" },
      { id: "20", name: "T. Almada", pos: "CAM", alt: ["CM"], rating: 81, club: "Atlético" },
      { id: "21", name: "A. Mac Allister", pos: "CB", rating: 76, club: "Union SG" },
      { id: "22", name: "V. Barco", pos: "LB", alt: ["LWB"], rating: 77, club: "Sevilla" },
    ],
  },
  {
    id: "japan", name: "Japan", flag: "🇯🇵", group: "F",
    players: [
      { id: "1", name: "Z. Suzuki", pos: "GK", rating: 79, club: "Parma" },
      { id: "2", name: "D. Hayashi", pos: "GK", rating: 75, club: "Stuttgart" },
      { id: "3", name: "H. Sakai", pos: "RB", alt: ["RWB"], rating: 76, club: "Auxerre" },
      { id: "4", name: "K. Itakura", pos: "CB", rating: 80, club: "Ajax" },
      { id: "5", name: "S. Tomiyasu", pos: "CB", alt: ["RB"], rating: 80, club: "Arsenal" },
      { id: "6", name: "T. Itakura", pos: "CB", rating: 78, club: "Borussia M." },
      { id: "7", name: "H. Watanabe", pos: "CB", rating: 76, club: "Feyenoord" },
      { id: "8", name: "Y. Itō", pos: "RWB", alt: ["RB", "RM"], rating: 78, club: "Bayern" },
      { id: "9", name: "K. Machida", pos: "CB", rating: 76, club: "Union Berlin" },
      { id: "10", name: "W. Endō", pos: "CDM", alt: ["CM"], rating: 80, club: "Liverpool" },
      { id: "11", name: "H. Morita", pos: "CDM", alt: ["CM"], rating: 79, club: "Sporting CP" },
      { id: "12", name: "D. Kamada", pos: "CAM", alt: ["CM"], rating: 80, club: "Crystal Palace" },
      { id: "13", name: "T. Minamino", pos: "CAM", alt: ["LW", "RW"], rating: 79, club: "Monaco" },
      { id: "14", name: "T. Kubo", pos: "RW", alt: ["CAM", "LW"], rating: 83, club: "Real Sociedad" },
      { id: "15", name: "K. Mitoma", pos: "LW", alt: ["RW"], rating: 83, club: "Brighton" },
      { id: "16", name: "R. Doan", pos: "RW", alt: ["LW"], rating: 80, club: "Eintracht" },
      { id: "17", name: "A. Ueda", pos: "ST", rating: 79, club: "Feyenoord" },
      { id: "18", name: "D. Maeda", pos: "ST", alt: ["LW"], rating: 79, club: "Celtic" },
      { id: "19", name: "K. Ueda", pos: "ST", rating: 75, club: "Lazio" },
      { id: "20", name: "T. Tanaka", pos: "CM", alt: ["CDM"], rating: 77, club: "Leeds" },
      { id: "21", name: "S. Nakamura", pos: "LB", alt: ["LWB"], rating: 76, club: "Reims" },
      { id: "22", name: "J. Ito", pos: "CM", rating: 75, club: "Genk" },
    ],
  },
  {
    id: "norway", name: "Norway", flag: "🇳🇴", group: "F",
    players: [
      { id: "1", name: "Ø. Nyland", pos: "GK", rating: 76, club: "Sevilla" },
      { id: "2", name: "E. Selvik", pos: "GK", rating: 73, club: "Viking" },
      { id: "3", name: "J. Ryerson", pos: "RB", alt: ["RWB"], rating: 78, club: "Dortmund" },
      { id: "4", name: "K. Ajer", pos: "CB", alt: ["RB"], rating: 78, club: "Brentford" },
      { id: "5", name: "L. Østigård", pos: "CB", rating: 78, club: "Rennes" },
      { id: "6", name: "S. Strandberg", pos: "CB", rating: 75, club: "Valerenga" },
      { id: "7", name: "B. Meling", pos: "LB", alt: ["LWB"], rating: 75, club: "Rennes" },
      { id: "8", name: "F. Bjørkan", pos: "LB", alt: ["LWB"], rating: 74, club: "Bodø/Glimt" },
      { id: "9", name: "M. Ødegaard", pos: "CAM", alt: ["CM", "RW"], rating: 86, club: "Arsenal" },
      { id: "10", name: "S. Berge", pos: "CM", alt: ["CDM"], rating: 78, club: "Fulham" },
      { id: "11", name: "F. Aursnes", pos: "CM", alt: ["LB", "CDM"], rating: 79, club: "Benfica" },
      { id: "12", name: "P. Berg", pos: "CDM", alt: ["CM"], rating: 76, club: "PSV" },
      { id: "13", name: "A. Nusa", pos: "LW", alt: ["RW"], rating: 80, club: "RB Leipzig" },
      { id: "14", name: "O. Bobb", pos: "RW", alt: ["LW"], rating: 78, club: "Man City" },
      { id: "15", name: "E. Haaland", pos: "ST", rating: 91, club: "Man City" },
      { id: "16", name: "A. Sørloth", pos: "ST", alt: ["CF"], rating: 83, club: "Atlético" },
      { id: "17", name: "J. Thorsby", pos: "CM", alt: ["RM"], rating: 76, club: "Genoa" },
      { id: "18", name: "M. Thorsby", pos: "CM", rating: 73, club: "Sarpsborg" },
      { id: "19", name: "K. Sørloth", pos: "RW", rating: 73, club: "Brann" },
      { id: "20", name: "H. Wolfe", pos: "RM", alt: ["RW"], rating: 73, club: "Rosenborg" },
    ],
  },
  {
    id: "panama", name: "Panama", flag: "🇵🇦", group: "F",
    players: [
      { id: "1", name: "O. Mosquera", pos: "GK", rating: 73, club: "Tauro FC" },
      { id: "2", name: "L. Mejía", pos: "GK", rating: 72, club: "Hatayspor" },
      { id: "3", name: "M. Murillo", pos: "RB", alt: ["RWB", "RM"], rating: 76, club: "New York City" },
      { id: "4", name: "R. Córdoba", pos: "CB", rating: 74, club: "Talleres" },
      { id: "5", name: "F. Escobar", pos: "CB", rating: 73, club: "Tigres" },
      { id: "6", name: "A. Andrade", pos: "CB", rating: 72, club: "FC Cincinnati" },
      { id: "7", name: "E. Bárcenas", pos: "LM", alt: ["LW"], rating: 74, club: "AVS" },
      { id: "8", name: "M. Vega", pos: "RB", alt: ["RWB"], rating: 71, club: "Sporting SM" },
      { id: "9", name: "A. Carrasquilla", pos: "CM", alt: ["CDM"], rating: 76, club: "Houston Dynamo" },
      { id: "10", name: "C. Martínez", pos: "CM", alt: ["CAM"], rating: 74, club: "Cartagena" },
      { id: "11", name: "I. Díaz", pos: "RW", alt: ["LW"], rating: 75, club: "FC Cincinnati" },
      { id: "12", name: "J. Fajardo", pos: "ST", alt: ["CF"], rating: 73, club: "Sporting SM" },
      { id: "13", name: "C. Harvey", pos: "CM", rating: 72, club: "Tauro FC" },
      { id: "14", name: "E. Davis", pos: "LB", alt: ["LWB"], rating: 73, peak: 76, club: "Independiente" },
      { id: "15", name: "J. Rodríguez", pos: "RW", alt: ["ST"], rating: 73, club: "DC United" },
      { id: "16", name: "C. Tanner", pos: "ST", rating: 73, club: "FC Dallas" },
      { id: "17", name: "A. Godoy", pos: "CDM", alt: ["CM"], rating: 73, club: "Nashville SC" },
      { id: "18", name: "G. Torres", pos: "ST", rating: 72, club: "Colón" },
      { id: "19", name: "J. Welch", pos: "CB", rating: 71, club: "Plaza Amador" },
      { id: "20", name: "A. Murillo", pos: "RW", rating: 71, club: "Plaza Amador" },
      { id: "21", name: "C. Blackman", pos: "ST", rating: 71, club: "CD Árabe Unido" },
    ],
  },
  // ─────────────────────────── GROUP G ───────────────────────────
  {
    id: "england", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "G",
    players: [
      { id: "1", name: "J. Pickford", pos: "GK", rating: 84, club: "Everton" },
      { id: "2", name: "D. Henderson", pos: "GK", rating: 79, club: "Crystal Palace" },
      { id: "3", name: "K. Walker", pos: "RB", alt: ["RWB", "CB"], rating: 81, peak: 86, club: "Burnley" },
      { id: "4", name: "T. Alexander-Arnold", pos: "RB", alt: ["RWB", "CM"], rating: 85, club: "Real Madrid" },
      { id: "5", name: "J. Stones", pos: "CB", alt: ["RB", "CDM"], rating: 84, club: "Man City" },
      { id: "6", name: "M. Guéhi", pos: "CB", rating: 83, club: "Crystal Palace" },
      { id: "7", name: "E. Konsa", pos: "CB", alt: ["RB"], rating: 80, club: "Aston Villa" },
      { id: "8", name: "L. Shaw", pos: "LB", alt: ["LWB", "CB"], rating: 80, club: "Man Utd" },
      { id: "9", name: "D. Rice", pos: "CDM", alt: ["CM"], rating: 87, club: "Arsenal" },
      { id: "10", name: "J. Bellingham", pos: "CAM", alt: ["CM"], rating: 88, club: "Real Madrid" },
      { id: "11", name: "P. Foden", pos: "CAM", alt: ["RW", "CM"], rating: 87, club: "Man City" },
      { id: "12", name: "C. Palmer", pos: "CAM", alt: ["RW"], rating: 85, club: "Chelsea" },
      { id: "13", name: "K. Phillips", pos: "CDM", rating: 76, peak: 82, club: "Ipswich" },
      { id: "14", name: "A. Wharton", pos: "CDM", alt: ["CM"], rating: 80, club: "Crystal Palace" },
      { id: "15", name: "B. Saka", pos: "RW", alt: ["RWB"], rating: 87, club: "Arsenal" },
      { id: "16", name: "P. Foden", pos: "LW", rating: 84, club: "Man City" },
      { id: "17", name: "A. Gordon", pos: "LW", alt: ["RW", "ST"], rating: 82, club: "Newcastle" },
      { id: "18", name: "M. Rashford", pos: "LW", alt: ["ST"], rating: 82, peak: 85, club: "Barcelona" },
      { id: "19", name: "H. Kane", pos: "ST", rating: 89, club: "Bayern" },
      { id: "20", name: "O. Watkins", pos: "ST", rating: 83, club: "Aston Villa" },
      { id: "21", name: "J. Gomez", pos: "RB", alt: ["CB"], rating: 78, club: "Liverpool" },
      { id: "22", name: "E. Anderson", pos: "CM", alt: ["CDM"], rating: 78, club: "Nottm Forest" },
    ],
  },
  {
    id: "switzerland", name: "Switzerland", flag: "🇨🇭", group: "G",
    players: [
      { id: "1", name: "Y. Sommer", pos: "GK", rating: 83, club: "Inter" },
      { id: "2", name: "G. Kobel", pos: "GK", rating: 82, club: "Dortmund" },
      { id: "3", name: "S. Widmer", pos: "RB", alt: ["RWB"], rating: 76, club: "Mainz" },
      { id: "4", name: "M. Akanji", pos: "CB", alt: ["RB"], rating: 84, club: "Inter" },
      { id: "5", name: "N. Elvedi", pos: "CB", rating: 78, club: "Borussia M." },
      { id: "6", name: "F. Schär", pos: "CB", rating: 80, club: "Newcastle" },
      { id: "7", name: "R. Rodríguez", pos: "LB", alt: ["LWB", "CB"], rating: 77, peak: 82, club: "Real Betis" },
      { id: "8", name: "S. Lotomba", pos: "RB", alt: ["RWB"], rating: 75, club: "Nice" },
      { id: "9", name: "G. Xhaka", pos: "CM", alt: ["CDM"], rating: 84, club: "Sunderland" },
      { id: "10", name: "R. Freuler", pos: "CDM", alt: ["CM"], rating: 79, club: "Bologna" },
      { id: "11", name: "D. Zakaria", pos: "CDM", alt: ["CM"], rating: 80, club: "Monaco" },
      { id: "12", name: "M. Aebischer", pos: "CM", alt: ["CDM"], rating: 77, club: "Pisa" },
      { id: "13", name: "X. Shaqiri", pos: "RW", alt: ["CAM"], rating: 78, peak: 84, club: "FC Basel" },
      { id: "14", name: "R. Vargas", pos: "LW", alt: ["ST", "RW"], rating: 79, club: "Sevilla" },
      { id: "15", name: "D. Ndoye", pos: "RW", alt: ["LW"], rating: 80, club: "Nottm Forest" },
      { id: "16", name: "B. Embolo", pos: "ST", alt: ["RW"], rating: 80, club: "Rennes" },
      { id: "17", name: "Z. Amdouni", pos: "ST", alt: ["CF"], rating: 77, club: "Benfica" },
      { id: "18", name: "C. Itten", pos: "ST", rating: 74, club: "Young Boys" },
      { id: "19", name: "F. Rieder", pos: "CM", alt: ["CAM"], rating: 78, club: "Rennes" },
      { id: "20", name: "V. Sierro", pos: "CM", rating: 75, club: "Toulouse" },
    ],
  },
  {
    id: "nigeria", name: "Nigeria", flag: "🇳🇬", group: "G",
    players: [
      { id: "1", name: "S. Nwabali", pos: "GK", rating: 76, club: "Chippa United" },
      { id: "2", name: "F. Uzoho", pos: "GK", rating: 74, club: "Omonia" },
      { id: "3", name: "O. Aina", pos: "RB", alt: ["RWB", "LB"], rating: 79, club: "Nottm Forest" },
      { id: "4", name: "W. Troost-Ekong", pos: "CB", rating: 78, club: "Al-Kholood" },
      { id: "5", name: "C. Bassey", pos: "CB", alt: ["LB"], rating: 79, club: "Fulham" },
      { id: "6", name: "B. Aribo", pos: "CM", alt: ["CAM"], rating: 76, club: "Southampton" },
      { id: "7", name: "Z. Sanusi", pos: "LB", alt: ["LWB"], rating: 76, club: "Porto" },
      { id: "8", name: "S. Chukwueze", pos: "RW", alt: ["LW"], rating: 80, club: "AC Milan" },
      { id: "9", name: "A. Iwobi", pos: "CM", alt: ["LW", "CAM"], rating: 80, club: "Fulham" },
      { id: "10", name: "F. Onyeka", pos: "CDM", alt: ["CM"], rating: 76, club: "Brentford" },
      { id: "11", name: "A. Lookman", pos: "LW", alt: ["ST", "RW"], rating: 83, club: "Atalanta" },
      { id: "12", name: "W. Ndidi", pos: "CDM", alt: ["CM", "CB"], rating: 80, club: "Besiktas" },
      { id: "13", name: "F. Tomori", pos: "CB", rating: 80, club: "AC Milan" },
      { id: "14", name: "R. Aina", pos: "RWB", alt: ["RB"], rating: 75, club: "Antalyaspor" },
      { id: "15", name: "V. Osimhen", pos: "ST", rating: 88, club: "Galatasaray" },
      { id: "16", name: "T. Awoniyi", pos: "ST", rating: 78, club: "Nottm Forest" },
      { id: "17", name: "K. Dennis", pos: "RW", alt: ["ST"], rating: 76, club: "Hellas Verona" },
      { id: "18", name: "C. Ugbo", pos: "ST", rating: 74, club: "Hull City" },
      { id: "19", name: "J. Iyenoma", pos: "CM", alt: ["CDM"], rating: 74, club: "Hapoel BS" },
      { id: "20", name: "G. Bello", pos: "LB", alt: ["LWB"], rating: 74, club: "FC Augsburg" },
      { id: "21", name: "C. Onuachu", pos: "ST", rating: 76, club: "Trabzonspor" },
    ],
  },
  {
    id: "bolivia", name: "Bolivia", flag: "🇧🇴", group: "G",
    players: [
      { id: "1", name: "C. Lampe", pos: "GK", rating: 73, club: "Always Ready" },
      { id: "2", name: "G. Viscarra", pos: "GK", rating: 73, club: "Alianza Lima" },
      { id: "3", name: "D. Bejarano", pos: "RB", alt: ["RWB"], rating: 71, club: "Bolívar" },
      { id: "4", name: "L. Haquín", pos: "CB", rating: 71, club: "Cancún FC" },
      { id: "5", name: "J. Sagredo", pos: "CB", rating: 70, club: "Bolívar" },
      { id: "6", name: "R. Fernández", pos: "CB", rating: 70, club: "The Strongest" },
      { id: "7", name: "R. Jusino", pos: "LB", alt: ["LWB", "CB"], rating: 71, club: "Real Tomayapo" },
      { id: "8", name: "H. Cuéllar", pos: "CDM", alt: ["CM"], rating: 71, club: "Bolívar" },
      { id: "9", name: "G. Villamil", pos: "CM", alt: ["CAM"], rating: 72, club: "Bolívar" },
      { id: "10", name: "M. Vaca", pos: "CAM", alt: ["CM"], rating: 72, club: "Always Ready" },
      { id: "11", name: "R. Vaca", pos: "CM", rating: 71, club: "Atlético Cearense" },
      { id: "12", name: "C. Álvarez", pos: "CM", alt: ["RM"], rating: 71, club: "Bolívar" },
      { id: "13", name: "M. Bruno Miranda", pos: "RW", alt: ["LW"], rating: 71, club: "Always Ready" },
      { id: "14", name: "J. Arce", pos: "ST", rating: 72, club: "Bolívar" },
      { id: "15", name: "E. Vaca", pos: "RW", alt: ["LW"], rating: 71, club: "The Strongest" },
      { id: "16", name: "C. Terceros", pos: "LW", alt: ["RW"], rating: 70, club: "Always Ready" },
      { id: "17", name: "F. Saucedo", pos: "CAM", alt: ["RW"], rating: 71, club: "Always Ready" },
      { id: "18", name: "E. Justiniano", pos: "ST", rating: 70, club: "Blooming" },
      { id: "19", name: "D. Roca", pos: "CDM", rating: 70, club: "Bolívar" },
      { id: "20", name: "L. Castro", pos: "ST", rating: 70, club: "Always Ready" },
      { id: "21", name: "P. Galindo", pos: "RB", alt: ["RWB"], rating: 70, club: "The Strongest" },
    ],
  },
  // ─────────────────────────── GROUP H ───────────────────────────
  {
    id: "brazil", name: "Brazil", flag: "🇧🇷", group: "H",
    players: [
      { id: "1", name: "Alisson", pos: "GK", rating: 88, club: "Liverpool" },
      { id: "2", name: "Ederson", pos: "GK", rating: 85, club: "Fenerbahçe" },
      { id: "3", name: "Danilo", pos: "RB", alt: ["CB", "RWB"], rating: 79, peak: 84, club: "Flamengo" },
      { id: "4", name: "Marquinhos", pos: "CB", rating: 86, club: "PSG" },
      { id: "5", name: "Gabriel Magalhães", pos: "CB", rating: 86, club: "Arsenal" },
      { id: "6", name: "É. Militão", pos: "CB", alt: ["RB"], rating: 84, club: "Real Madrid" },
      { id: "7", name: "Wesley", pos: "RB", alt: ["RWB"], rating: 79, club: "Roma" },
      { id: "8", name: "A. Carlos", pos: "LB", alt: ["LWB"], rating: 81, club: "Juventus" },
      { id: "9", name: "G. Arana", pos: "LB", alt: ["LWB"], rating: 78, club: "Atlético MG" },
      { id: "10", name: "Bruno Guimarães", pos: "CM", alt: ["CDM"], rating: 86, club: "Newcastle" },
      { id: "11", name: "Casemiro", pos: "CDM", rating: 81, peak: 89, club: "Man Utd" },
      { id: "12", name: "André", pos: "CDM", alt: ["CM"], rating: 80, club: "Wolves" },
      { id: "13", name: "Lucas Paquetá", pos: "CAM", alt: ["CM"], rating: 82, club: "West Ham" },
      { id: "14", name: "Vinícius Jr", pos: "LW", alt: ["ST"], rating: 90, club: "Real Madrid" },
      { id: "15", name: "Rodrygo", pos: "RW", alt: ["LW", "ST"], rating: 85, club: "Real Madrid" },
      { id: "16", name: "Raphinha", pos: "RW", alt: ["LW"], rating: 87, club: "Barcelona" },
      { id: "17", name: "Savinho", pos: "RW", alt: ["LW"], rating: 81, club: "Man City" },
      { id: "18", name: "Estêvão", pos: "RW", alt: ["LW", "CAM"], rating: 82, club: "Chelsea" },
      { id: "19", name: "Endrick", pos: "ST", rating: 80, club: "Real Madrid" },
      { id: "20", name: "Matheus Cunha", pos: "ST", alt: ["CF", "LW"], rating: 82, club: "Man Utd" },
      { id: "21", name: "João Pedro", pos: "ST", alt: ["CF"], rating: 81, club: "Chelsea" },
      { id: "22", name: "Gerson", pos: "CM", alt: ["CDM"], rating: 80, club: "Zenit" },
    ],
  },
  {
    id: "denmark", name: "Denmark", flag: "🇩🇰", group: "H",
    players: [
      { id: "1", name: "K. Schmeichel", pos: "GK", rating: 80, peak: 84, club: "Celtic" },
      { id: "2", name: "M. Hansen", pos: "GK", rating: 77, club: "PSV" },
      { id: "3", name: "J. Andersen", pos: "CB", rating: 82, club: "Crystal Palace" },
      { id: "4", name: "A. Christensen", pos: "CB", alt: ["CDM"], rating: 82, club: "Barcelona" },
      { id: "5", name: "J. Vestergaard", pos: "CB", rating: 79, club: "Leicester" },
      { id: "6", name: "V. Kristiansen", pos: "LB", alt: ["LWB"], rating: 77, club: "Leicester" },
      { id: "7", name: "R. Kristensen", pos: "RB", alt: ["RWB", "CB"], rating: 76, club: "Eintracht" },
      { id: "8", name: "J. Mæhle", pos: "LB", alt: ["LWB", "RB"], rating: 77, club: "Wolfsburg" },
      { id: "9", name: "P. Højbjerg", pos: "CDM", alt: ["CM"], rating: 81, club: "Marseille" },
      { id: "10", name: "M. Hjulmand", pos: "CDM", alt: ["CM"], rating: 80, club: "Sporting CP" },
      { id: "11", name: "C. Eriksen", pos: "CAM", alt: ["CM"], rating: 80, peak: 88, club: "Wolfsburg" },
      { id: "12", name: "M. Damsgaard", pos: "CAM", alt: ["LW", "RW"], rating: 80, club: "Brentford" },
      { id: "13", name: "M. Wind", pos: "ST", alt: ["LW"], rating: 78, club: "Leicester" },
      { id: "14", name: "A. Skov Olsen", pos: "RW", alt: ["LW"], rating: 79, club: "Club Brugge" },
      { id: "15", name: "J. Bruun Larsen", pos: "LW", alt: ["RW"], rating: 75, club: "FC Copenhagen" },
      { id: "16", name: "R. Højlund", pos: "ST", rating: 80, club: "Napoli" },
      { id: "17", name: "J. Dolberg", pos: "ST", rating: 77, club: "Ajax" },
      { id: "18", name: "C. Nørgaard", pos: "CDM", alt: ["CM"], rating: 78, club: "Arsenal" },
      { id: "19", name: "M. Frese", pos: "RB", alt: ["RWB"], rating: 74, club: "Mainz" },
      { id: "20", name: "G. Kofane", pos: "ST", rating: 73, club: "FC Copenhagen" },
    ],
  },
  {
    id: "ivory-coast", name: "Ivory Coast", flag: "🇨🇮", group: "H",
    players: [
      { id: "1", name: "Y. Fofana", pos: "GK", rating: 74, club: "Stade d'Abidjan" },
      { id: "2", name: "B. Sangaré", pos: "GK", rating: 73, club: "ESTAC Troyes" },
      { id: "3", name: "S. Aurier", pos: "RB", alt: ["RWB"], rating: 76, peak: 82, club: "FC Sochaux" },
      { id: "4", name: "O. Diakité", pos: "CB", rating: 76, club: "Almería" },
      { id: "5", name: "E. Ndicka", pos: "CB", alt: ["LB"], rating: 81, club: "Roma" },
      { id: "6", name: "W. Boly", pos: "CB", rating: 76, peak: 80, club: "Al-Duhail" },
      { id: "7", name: "G. Konan", pos: "LB", alt: ["LWB"], rating: 76, club: "FC Nantes" },
      { id: "8", name: "S. Singo", pos: "RB", alt: ["RWB", "RM"], rating: 80, club: "Monaco" },
      { id: "9", name: "F. Kessié", pos: "CM", alt: ["CDM"], rating: 81, club: "Al-Ahli" },
      { id: "10", name: "I. Sangaré", pos: "CDM", alt: ["CM"], rating: 78, club: "Nottm Forest" },
      { id: "11", name: "S. Fofana", pos: "CDM", alt: ["CM"], rating: 79, club: "Lens" },
      { id: "12", name: "F. Kessié", pos: "CM", rating: 75, club: "ASEC Mimosas" },
      { id: "13", name: "N. Pépé", pos: "RW", alt: ["LW"], rating: 78, peak: 83, club: "Villarreal" },
      { id: "14", name: "S. Haller", pos: "ST", rating: 79, peak: 83, club: "Utrecht" },
      { id: "15", name: "J. Diakité", pos: "RW", alt: ["LW"], rating: 75, club: "Lorient" },
      { id: "16", name: "S. Krasso", pos: "ST", alt: ["CF"], rating: 76, club: "Panathinaikos" },
      { id: "17", name: "M. Gradel", pos: "LW", alt: ["RW"], rating: 74, peak: 80, club: "Gaziantep" },
      { id: "18", name: "C. Adingra", pos: "LW", alt: ["RW"], rating: 79, club: "Sunderland" },
      { id: "19", name: "J. Kouamé", pos: "ST", alt: ["RW"], rating: 76, club: "Hoffenheim" },
      { id: "20", name: "O. Diomandé", pos: "CB", rating: 77, club: "Sporting CP" },
      { id: "21", name: "F. Diallo", pos: "RW", alt: ["LW"], rating: 76, club: "PSG" },
    ],
  },
  {
    id: "costa-rica", name: "Costa Rica", flag: "🇨🇷", group: "H",
    players: [
      { id: "1", name: "K. Navas", pos: "GK", rating: 80, peak: 87, club: "Pumas" },
      { id: "2", name: "P. Sequeira", pos: "GK", rating: 73, club: "Alajuelense" },
      { id: "3", name: "K. Fuller", pos: "RB", alt: ["RWB"], rating: 74, club: "Wycombe" },
      { id: "4", name: "F. Calvo", pos: "CB", rating: 75, club: "Al-Batin" },
      { id: "5", name: "J. Vargas", pos: "CB", rating: 73, club: "Alajuelense" },
      { id: "6", name: "J. Martínez", pos: "CB", rating: 73, club: "Saprissa" },
      { id: "7", name: "C. Gamboa", pos: "RB", alt: ["RWB"], rating: 73, peak: 77, club: "Saprissa" },
      { id: "8", name: "F. Mora", pos: "LB", alt: ["LWB"], rating: 73, club: "Herediano" },
      { id: "9", name: "Y. Aguilera", pos: "CM", alt: ["CAM"], rating: 75, club: "Saprissa" },
      { id: "10", name: "C. Borges", pos: "CM", alt: ["CDM"], rating: 74, club: "Saprissa" },
      { id: "11", name: "O. Duarte", pos: "CDM", alt: ["CB"], rating: 73, club: "Al-Wehda" },
      { id: "12", name: "B. Oviedo", pos: "LB", alt: ["LWB"], rating: 73, peak: 78, club: "Saprissa" },
      { id: "13", name: "J. Campbell", pos: "RW", alt: ["ST"], rating: 75, peak: 80, club: "Saprissa" },
      { id: "14", name: "A. Contreras", pos: "RW", alt: ["LW"], rating: 73, club: "Alajuelense" },
      { id: "15", name: "M. Ugalde", pos: "ST", alt: ["CF"], rating: 76, club: "Saprissa" },
      { id: "16", name: "A. Zamora", pos: "ST", rating: 74, club: "Herediano" },
      { id: "17", name: "C. Mora", pos: "CM", rating: 73, club: "Saprissa" },
      { id: "18", name: "B. Wilson", pos: "LW", alt: ["RW"], rating: 72, club: "Herediano" },
      { id: "19", name: "W. Tejeda", pos: "CDM", rating: 72, club: "Herediano" },
      { id: "20", name: "A. Salas", pos: "ST", rating: 71, club: "Alajuelense" },
      { id: "21", name: "J. Aguilera", pos: "RW", alt: ["LW"], rating: 71, club: "Herediano" },
    ],
  },
];
