import type { Nation } from "../types";

// Groups A–D. Ratings reflect approximate 2025/26 form; `peak` set where a
// player's career-best clearly exceeds current form.
export const PART1: Nation[] = [
  // ─────────────────────────── GROUP A ───────────────────────────
  {
    id: "mexico", name: "Mexico", flag: "🇲🇽", group: "A",
    players: [
      { id: "1", name: "G. Ochoa", pos: "GK", rating: 78, peak: 84, club: "AVS" },
      { id: "2", name: "L. Malagón", pos: "GK", rating: 80, club: "América" },
      { id: "3", name: "J. Sánchez", pos: "RB", alt: ["RWB"], rating: 79, club: "Cruz Azul" },
      { id: "4", name: "C. Montes", pos: "CB", rating: 80, club: "Espanyol" },
      { id: "5", name: "J. Vásquez", pos: "CB", alt: ["RB"], rating: 79, club: "West Ham" },
      { id: "6", name: "J. Araujo", pos: "LB", alt: ["LWB"], rating: 78, club: "Ajax" },
      { id: "7", name: "I. Sánchez", pos: "CB", rating: 76, club: "Tigres" },
      { id: "8", name: "J. Gallardo", pos: "LB", alt: ["LM"], rating: 78, club: "Toluca" },
      { id: "9", name: "E. Álvarez", pos: "CDM", alt: ["CM"], rating: 83, club: "Fenerbahçe" },
      { id: "10", name: "L. Chávez", pos: "CM", alt: ["CAM"], rating: 79, club: "QPR" },
      { id: "11", name: "C. Rodríguez", pos: "LM", alt: ["LW"], rating: 80, club: "Feyenoord" },
      { id: "12", name: "O. Pineda", pos: "CM", rating: 77, club: "Toluca" },
      { id: "13", name: "L. Romo", pos: "CM", alt: ["RB"], rating: 79, club: "Rayados" },
      { id: "14", name: "D. Lainez", pos: "RW", alt: ["LW"], rating: 77, club: "Tigres" },
      { id: "15", name: "H. Lozano", pos: "RW", alt: ["LW"], rating: 82, peak: 84, club: "San Diego FC" },
      { id: "16", name: "A. Vega", pos: "CAM", alt: ["RW"], rating: 78, club: "Monterrey" },
      { id: "17", name: "S. Giménez", pos: "ST", rating: 82, club: "AC Milan" },
      { id: "18", name: "R. Jiménez", pos: "ST", alt: ["CF"], rating: 80, peak: 83, club: "Fulham" },
      { id: "19", name: "G. Martín", pos: "ST", alt: ["CF"], rating: 76, club: "América" },
      { id: "20", name: "R. Pizarro", pos: "CAM", rating: 75, club: "Pachuca" },
      { id: "21", name: "J. Ruiz", pos: "RW", alt: ["LM"], rating: 75, club: "Pumas" },
    ],
  },
  {
    id: "croatia", name: "Croatia", flag: "🇭🇷", group: "A",
    players: [
      { id: "1", name: "D. Livaković", pos: "GK", rating: 82, club: "Fenerbahçe" },
      { id: "2", name: "I. Nevistić", pos: "GK", rating: 76, club: "Dinamo Zagreb" },
      { id: "3", name: "J. Stanišić", pos: "RB", alt: ["CB"], rating: 81, club: "Bayern" },
      { id: "4", name: "J. Gvardiol", pos: "CB", alt: ["LB"], rating: 86, club: "Man City" },
      { id: "5", name: "J. Šutalo", pos: "CB", rating: 79, club: "Ajax" },
      { id: "6", name: "M. Pongračić", pos: "CB", rating: 79, club: "Fiorentina" },
      { id: "7", name: "B. Sosa", pos: "LB", alt: ["LWB"], rating: 79, club: "Ajax" },
      { id: "8", name: "M. Erlić", pos: "CB", rating: 77, club: "Sassuolo" },
      { id: "9", name: "L. Modrić", pos: "CM", alt: ["CAM"], rating: 86, peak: 91, club: "AC Milan" },
      { id: "10", name: "M. Kovačić", pos: "CM", alt: ["CDM"], rating: 84, club: "Man City" },
      { id: "11", name: "M. Brozović", pos: "CDM", alt: ["CM"], rating: 82, peak: 86, club: "Al-Nassr" },
      { id: "12", name: "L. Sučić", pos: "CM", alt: ["CAM"], rating: 80, club: "RB Leipzig" },
      { id: "13", name: "N. Vlašić", pos: "CAM", alt: ["RW"], rating: 79, club: "Torino" },
      { id: "14", name: "M. Pašalić", pos: "CAM", alt: ["CM"], rating: 79, club: "Atalanta" },
      { id: "15", name: "L. Majer", pos: "CM", rating: 78, club: "Wolfsburg" },
      { id: "16", name: "I. Perišić", pos: "LW", alt: ["LWB"], rating: 81, peak: 85, club: "PSV" },
      { id: "17", name: "A. Kramarić", pos: "ST", alt: ["CAM"], rating: 81, club: "Hoffenheim" },
      { id: "18", name: "A. Budimir", pos: "ST", rating: 80, club: "Osasuna" },
      { id: "19", name: "I. Sučić", pos: "CM", rating: 76, club: "Salzburg" },
      { id: "20", name: "M. Baturina", pos: "CAM", alt: ["RW"], rating: 78, club: "Dinamo Zagreb" },
      { id: "21", name: "D. Vušković", pos: "CB", rating: 75, club: "Hajduk Split" },
    ],
  },
  {
    id: "ecuador", name: "Ecuador", flag: "🇪🇨", group: "A",
    players: [
      { id: "1", name: "H. Galíndez", pos: "GK", rating: 77, club: "Huracán" },
      { id: "2", name: "A. Domínguez", pos: "GK", rating: 76, club: "Sporting Cristal" },
      { id: "3", name: "P. Estupiñán", pos: "LB", alt: ["LWB"], rating: 81, club: "AC Milan" },
      { id: "4", name: "Á. Preciado", pos: "RB", alt: ["RWB"], rating: 79, club: "Bragantino" },
      { id: "5", name: "P. Hincapié", pos: "CB", alt: ["LB"], rating: 84, club: "Bayer Leverkusen" },
      { id: "6", name: "W. Pacho", pos: "CB", rating: 84, club: "PSG" },
      { id: "7", name: "F. Torres", pos: "CB", rating: 77, club: "LAFC" },
      { id: "8", name: "J. Hurtado", pos: "RB", rating: 75, club: "Atlético MG" },
      { id: "9", name: "M. Caicedo", pos: "CDM", alt: ["CM"], rating: 86, club: "Chelsea" },
      { id: "10", name: "K. Sarmiento", pos: "CM", alt: ["CDM"], rating: 78, club: "Brighton" },
      { id: "11", name: "A. Franco", pos: "CM", rating: 76, club: "Austin FC" },
      { id: "12", name: "J. Cifuentes", pos: "CM", alt: ["CAM"], rating: 78, club: "Al-Ittihad" },
      { id: "13", name: "G. Plata", pos: "RW", alt: ["LW"], rating: 80, club: "Flamengo" },
      { id: "14", name: "K. Páez", pos: "CAM", alt: ["RW"], rating: 80, peak: 85, club: "Chelsea" },
      { id: "15", name: "P. Caicedo", pos: "RW", alt: ["ST"], rating: 75, club: "El Nacional" },
      { id: "16", name: "J. Rodríguez", pos: "ST", alt: ["RW"], rating: 78, club: "Toluca" },
      { id: "17", name: "E. Valencia", pos: "ST", rating: 80, peak: 83, club: "Inter MTL" },
      { id: "18", name: "L. Sinisterra", pos: "LW", alt: ["RW"], rating: 79, club: "Bournemouth" },
      { id: "19", name: "Á. Rodríguez", pos: "ST", rating: 75, club: "LDU Quito" },
      { id: "20", name: "J. Ordóñez", pos: "CB", rating: 77, club: "Brugge" },
    ],
  },
  {
    id: "qatar", name: "Qatar", flag: "🇶🇦", group: "A",
    players: [
      { id: "1", name: "M. Barsham", pos: "GK", rating: 73, club: "Al-Sadd" },
      { id: "2", name: "S. Al-Sheeb", pos: "GK", rating: 72, club: "Al-Sadd" },
      { id: "3", name: "P. Correia", pos: "RB", alt: ["RWB"], rating: 73, club: "Al-Sadd" },
      { id: "4", name: "B. Khoukhi", pos: "CB", rating: 74, club: "Al-Ahli" },
      { id: "5", name: "T. Salman", pos: "CB", rating: 73, club: "Al-Duhail" },
      { id: "6", name: "B. Mohammed", pos: "CB", rating: 73, club: "Al-Sadd" },
      { id: "7", name: "H. Ahmed", pos: "LB", alt: ["LWB"], rating: 72, club: "Al-Rayyan" },
      { id: "8", name: "A. Hassan", pos: "CDM", alt: ["CM"], rating: 73, club: "Al-Sadd" },
      { id: "9", name: "K. Boudiaf", pos: "CDM", alt: ["CB"], rating: 74, club: "Al-Duhail" },
      { id: "10", name: "H. Al-Haydos", pos: "CAM", alt: ["RW"], rating: 75, peak: 78, club: "Al-Sadd" },
      { id: "11", name: "A. Hatem", pos: "CM", alt: ["CAM"], rating: 73, club: "Al-Rayyan" },
      { id: "12", name: "M. Waad", pos: "CM", rating: 71, club: "Al-Sadd" },
      { id: "13", name: "I. Mohammed", pos: "RM", alt: ["RW"], rating: 72, club: "Al-Wakrah" },
      { id: "14", name: "A. Afif", pos: "CAM", alt: ["LW"], rating: 79, club: "Al-Sadd" },
      { id: "15", name: "A. Madibo", pos: "CDM", rating: 72, club: "Al-Duhail" },
      { id: "16", name: "Y. Mohammed", pos: "LW", alt: ["RW"], rating: 72, club: "Al-Gharafa" },
      { id: "17", name: "A. Ali", pos: "ST", alt: ["CF"], rating: 76, peak: 78, club: "Al-Duhail" },
      { id: "18", name: "M. Muntari", pos: "ST", rating: 73, club: "Al-Duhail" },
      { id: "19", name: "M. Montari", pos: "RW", alt: ["ST"], rating: 71, club: "Al-Wakrah" },
      { id: "20", name: "T. Hassan", pos: "ST", rating: 70, club: "Al-Arabi" },
      { id: "21", name: "A. Fadlalla", pos: "CB", rating: 71, club: "Al-Gharafa" },
    ],
  },
  // ─────────────────────────── GROUP B ───────────────────────────
  {
    id: "canada", name: "Canada", flag: "🇨🇦", group: "B",
    players: [
      { id: "1", name: "M. Crépeau", pos: "GK", rating: 77, club: "Portland Timbers" },
      { id: "2", name: "D. St. Clair", pos: "GK", rating: 75, club: "Minnesota Utd" },
      { id: "3", name: "A. Johnston", pos: "RB", alt: ["RWB"], rating: 79, club: "Celtic" },
      { id: "4", name: "M. Miller", pos: "CB", rating: 76, club: "CF Montréal" },
      { id: "5", name: "D. Vitória", pos: "CB", rating: 76, club: "FC Famalicão" },
      { id: "6", name: "M. Kone", pos: "CB", rating: 77, club: "Marseille" },
      { id: "7", name: "A. Davies", pos: "LB", alt: ["LW", "LWB"], rating: 85, club: "Bayern" },
      { id: "8", name: "S. Adekugbe", pos: "LB", rating: 74, club: "Bursaspor" },
      { id: "9", name: "S. Eustáquio", pos: "CDM", alt: ["CM"], rating: 80, club: "Porto" },
      { id: "10", name: "I. Koné", pos: "CM", alt: ["CDM"], rating: 80, club: "Marseille" },
      { id: "11", name: "J. David", pos: "ST", alt: ["CF"], rating: 84, club: "Juventus" },
      { id: "12", name: "T. Buchanan", pos: "RM", alt: ["RB", "RW"], rating: 79, club: "Inter" },
      { id: "13", name: "S. Larin", pos: "ST", rating: 77, club: "Mallorca" },
      { id: "14", name: "C. Hutchinson", pos: "CM", rating: 75, club: "CF Montréal" },
      { id: "15", name: "L. Millar", pos: "CM", alt: ["CAM"], rating: 75, club: "Hull City" },
      { id: "16", name: "J. Osorio", pos: "CAM", alt: ["CM"], rating: 76, club: "Toronto FC" },
      { id: "17", name: "T. Oluwaseyi", pos: "ST", alt: ["LW"], rating: 75, club: "Minnesota Utd" },
      { id: "18", name: "J. Shaffelburg", pos: "LW", alt: ["RW"], rating: 76, club: "Nashville SC" },
      { id: "19", name: "C. Bombito", pos: "CB", rating: 77, club: "Nice" },
      { id: "20", name: "R. Laryea", pos: "RB", alt: ["RWB"], rating: 75, club: "Toronto FC" },
      { id: "21", name: "A. Ahmed", pos: "RW", alt: ["LW"], rating: 76, club: "Toulouse" },
    ],
  },
  {
    id: "belgium", name: "Belgium", flag: "🇧🇪", group: "B",
    players: [
      { id: "1", name: "K. Casteels", pos: "GK", rating: 81, club: "Al-Qadsiah" },
      { id: "2", name: "M. Sels", pos: "GK", rating: 80, club: "Nottm Forest" },
      { id: "3", name: "T. Castagne", pos: "RB", alt: ["RWB"], rating: 79, club: "Fulham" },
      { id: "4", name: "W. Faes", pos: "CB", rating: 78, club: "Leicester" },
      { id: "5", name: "Z. Debast", pos: "CB", alt: ["CDM"], rating: 79, club: "Sporting CP" },
      { id: "6", name: "A. Theate", pos: "CB", alt: ["LB"], rating: 80, club: "Eintracht" },
      { id: "7", name: "M. De Cuyper", pos: "LB", alt: ["LWB"], rating: 78, club: "Brighton" },
      { id: "8", name: "K. De Bruyne", pos: "CAM", alt: ["CM"], rating: 88, peak: 91, club: "Napoli" },
      { id: "9", name: "A. Onana", pos: "CDM", alt: ["CM"], rating: 81, club: "Aston Villa" },
      { id: "10", name: "Y. Tielemans", pos: "CM", alt: ["CDM"], rating: 82, club: "Aston Villa" },
      { id: "11", name: "C. Nielsen", pos: "CM", rating: 76, club: "Anderlecht" },
      { id: "12", name: "J. Doku", pos: "LW", alt: ["RW"], rating: 83, club: "Man City" },
      { id: "13", name: "L. Trossard", pos: "LW", alt: ["ST"], rating: 82, club: "Arsenal" },
      { id: "14", name: "C. De Ketelaere", pos: "CAM", alt: ["ST", "RW"], rating: 81, club: "Atalanta" },
      { id: "15", name: "D. Bakayoko", pos: "RW", alt: ["LW"], rating: 78, club: "PSV" },
      { id: "16", name: "R. Lukaku", pos: "ST", rating: 84, peak: 88, club: "Napoli" },
      { id: "17", name: "L. Openda", pos: "ST", alt: ["LW"], rating: 81, club: "Juventus" },
      { id: "18", name: "M. Tchatchoua", pos: "RWB", alt: ["RB"], rating: 75, club: "Verona" },
      { id: "19", name: "A. Vermeeren", pos: "CDM", alt: ["CM"], rating: 78, club: "RB Leipzig" },
      { id: "20", name: "O. Mangala", pos: "CM", rating: 76, club: "Everton" },
      { id: "21", name: "M. Vanhoutte", pos: "LB", rating: 74, club: "Genoa" },
    ],
  },
  {
    id: "egypt", name: "Egypt", flag: "🇪🇬", group: "B",
    players: [
      { id: "1", name: "M. El Shenawy", pos: "GK", rating: 79, club: "Al Ahly" },
      { id: "2", name: "M. Abou Gabal", pos: "GK", rating: 75, club: "Al Ahly" },
      { id: "3", name: "A. Hegazi", pos: "CB", rating: 78, peak: 81, club: "Al-Ittihad" },
      { id: "4", name: "M. Abdelmonem", pos: "CB", rating: 77, club: "Galatasaray" },
      { id: "5", name: "O. Kamal", pos: "CB", rating: 75, club: "Zamalek" },
      { id: "6", name: "A. Fatouh", pos: "LB", alt: ["LWB"], rating: 75, club: "Al Ahly" },
      { id: "7", name: "M. Hamdy", pos: "RB", alt: ["RWB"], rating: 75, club: "Al Ahly" },
      { id: "8", name: "M. Elneny", pos: "CDM", alt: ["CM"], rating: 76, peak: 80, club: "Al-Jazira" },
      { id: "9", name: "M. Hamdy", pos: "CM", rating: 74, club: "Pyramids" },
      { id: "10", name: "M. Salah", pos: "RW", alt: ["ST", "LW"], rating: 89, peak: 91, club: "Liverpool" },
      { id: "11", name: "T. Hamed", pos: "CDM", alt: ["CM"], rating: 75, club: "Al Ahly" },
      { id: "12", name: "E. Hamdi", pos: "CM", alt: ["CAM"], rating: 75, club: "Al Ahly" },
      { id: "13", name: "M. Magdy", pos: "CM", rating: 74, club: "Al Ahly" },
      { id: "14", name: "O. Marmoush", pos: "ST", alt: ["RW", "LW"], rating: 84, club: "Man City" },
      { id: "15", name: "Z. Trezeguet", pos: "LW", alt: ["RW"], rating: 78, club: "Al Ahly" },
      { id: "16", name: "M. Sherif", pos: "ST", rating: 76, club: "Al Ahly" },
      { id: "17", name: "I. Adel", pos: "RW", alt: ["LW"], rating: 74, club: "Pyramids" },
      { id: "18", name: "A. Mostafa", pos: "RB", rating: 73, club: "Pyramids" },
      { id: "19", name: "A. Koka", pos: "ST", rating: 73, club: "Zamalek" },
      { id: "20", name: "M. Shehata", pos: "CAM", rating: 74, club: "Al Ahly" },
    ],
  },
  {
    id: "jordan", name: "Jordan", flag: "🇯🇴", group: "B",
    players: [
      { id: "1", name: "Y. Abulaila", pos: "GK", rating: 73, club: "Al-Wehdat" },
      { id: "2", name: "A. Abu Laila", pos: "GK", rating: 71, club: "Al-Ramtha" },
      { id: "3", name: "M. Abu Hasheesh", pos: "RB", alt: ["RWB"], rating: 72, club: "Al-Wehdat" },
      { id: "4", name: "Y. Rawashdeh", pos: "CB", rating: 73, club: "Al-Hussein" },
      { id: "5", name: "A. Nasib", pos: "CB", rating: 73, club: "Al-Ramtha" },
      { id: "6", name: "S. Mardi", pos: "LB", alt: ["LWB"], rating: 72, club: "Al-Wehdat" },
      { id: "7", name: "F. Al-Dmeiri", pos: "CB", rating: 71, club: "Al-Faisaly" },
      { id: "8", name: "N. Al-Rashdan", pos: "CDM", alt: ["CM"], rating: 74, club: "Al-Faisaly" },
      { id: "9", name: "E. Al-Tamari", pos: "RW", alt: ["LW", "ST"], rating: 78, club: "Montpellier" },
      { id: "10", name: "M. Al-Naimat", pos: "ST", alt: ["LW"], rating: 75, club: "Al-Wehdat" },
      { id: "11", name: "Y. Al-Naber", pos: "CAM", alt: ["RW"], rating: 73, club: "Al-Hussein" },
      { id: "12", name: "M. Abu Zraiq", pos: "CM", rating: 72, club: "Al-Wehdat" },
      { id: "13", name: "A. Kanaan", pos: "CM", alt: ["CAM"], rating: 73, club: "Al-Faisaly" },
      { id: "14", name: "Y. Al-Rawabdeh", pos: "RM", alt: ["RW"], rating: 72, club: "Al-Hussein" },
      { id: "15", name: "M. Al-Dmeiri", pos: "CM", rating: 71, club: "Al-Faisaly" },
      { id: "16", name: "A. Hayel", pos: "LW", alt: ["RW"], rating: 72, club: "Al-Wehdat" },
      { id: "17", name: "Y. Touqa", pos: "ST", rating: 73, club: "Al-Ahli" },
      { id: "18", name: "B. Shelbaieh", pos: "CAM", alt: ["ST"], rating: 73, club: "Al-Hussein" },
      { id: "19", name: "M. Othman", pos: "CB", rating: 71, club: "Al-Salt" },
      { id: "20", name: "A. Al-Arab", pos: "ST", rating: 70, club: "Shabab Al-Ordon" },
      { id: "21", name: "M. Abu Hashish", pos: "RB", alt: ["RWB"], rating: 71, club: "Al-Hussein" },
    ],
  },
  // ─────────────────────────── GROUP C ───────────────────────────
  {
    id: "spain", name: "Spain", flag: "🇪🇸", group: "C",
    players: [
      { id: "1", name: "U. Simón", pos: "GK", rating: 86, club: "Athletic Club" },
      { id: "2", name: "D. Raya", pos: "GK", rating: 84, club: "Arsenal" },
      { id: "3", name: "P. Porro", pos: "RB", alt: ["RWB"], rating: 81, club: "Tottenham" },
      { id: "4", name: "D. Carvajal", pos: "RB", alt: ["RWB"], rating: 85, club: "Real Madrid" },
      { id: "5", name: "P. Cubarsí", pos: "CB", rating: 83, club: "Barcelona" },
      { id: "6", name: "R. Le Normand", pos: "CB", rating: 83, club: "Atlético" },
      { id: "7", name: "A. Laporte", pos: "CB", rating: 83, club: "Athletic Club" },
      { id: "8", name: "M. Cucurella", pos: "LB", alt: ["LWB"], rating: 83, club: "Chelsea" },
      { id: "9", name: "A. Grimaldo", pos: "LB", alt: ["LWB", "LM"], rating: 83, club: "Bayer Leverkusen" },
      { id: "10", name: "Rodri", pos: "CDM", alt: ["CM"], rating: 90, club: "Man City" },
      { id: "11", name: "Pedri", pos: "CM", alt: ["CAM"], rating: 87, club: "Barcelona" },
      { id: "12", name: "Gavi", pos: "CM", alt: ["CAM"], rating: 83, club: "Barcelona" },
      { id: "13", name: "F. Ruiz", pos: "CM", alt: ["CAM"], rating: 84, club: "PSG" },
      { id: "14", name: "M. Merino", pos: "CM", alt: ["CDM"], rating: 82, club: "Arsenal" },
      { id: "15", name: "M. Zubimendi", pos: "CDM", rating: 84, club: "Arsenal" },
      { id: "16", name: "Lamine Yamal", pos: "RW", alt: ["LW"], rating: 88, peak: 92, club: "Barcelona" },
      { id: "17", name: "N. Williams", pos: "LW", alt: ["RW"], rating: 85, club: "Barcelona" },
      { id: "18", name: "D. Olmo", pos: "CAM", alt: ["LW"], rating: 85, club: "Barcelona" },
      { id: "19", name: "Á. Morata", pos: "ST", rating: 81, peak: 84, club: "Como" },
      { id: "20", name: "M. Oyarzabal", pos: "ST", alt: ["LW"], rating: 83, club: "Real Sociedad" },
      { id: "21", name: "F. Torres", pos: "ST", alt: ["CF"], rating: 82, club: "Barcelona" },
      { id: "22", name: "Á. Baena", pos: "CAM", alt: ["LW"], rating: 81, club: "Atlético" },
    ],
  },
  {
    id: "uruguay", name: "Uruguay", flag: "🇺🇾", group: "C",
    players: [
      { id: "1", name: "S. Rochet", pos: "GK", rating: 79, club: "Inter MIA" },
      { id: "2", name: "F. Muslera", pos: "GK", rating: 76, peak: 82, club: "Galatasaray" },
      { id: "3", name: "N. Nández", pos: "RB", alt: ["RWB", "CM"], rating: 80, club: "Al-Qadsiah" },
      { id: "4", name: "R. Araújo", pos: "CB", alt: ["RB"], rating: 85, club: "Barcelona" },
      { id: "5", name: "J. Giménez", pos: "CB", rating: 85, club: "Atlético" },
      { id: "6", name: "S. Coates", pos: "CB", rating: 78, peak: 82, club: "Sporting CP" },
      { id: "7", name: "M. Olivera", pos: "LB", alt: ["LWB"], rating: 80, club: "Napoli" },
      { id: "8", name: "G. Varela", pos: "RB", alt: ["RWB"], rating: 78, club: "Flamengo" },
      { id: "9", name: "F. Valverde", pos: "CM", alt: ["CDM", "RM"], rating: 89, club: "Real Madrid" },
      { id: "10", name: "M. Ugarte", pos: "CDM", rating: 81, club: "Man Utd" },
      { id: "11", name: "R. Bentancur", pos: "CM", alt: ["CDM"], rating: 82, club: "Tottenham" },
      { id: "12", name: "N. de la Cruz", pos: "CAM", alt: ["CM"], rating: 81, club: "Flamengo" },
      { id: "13", name: "G. de Arrascaeta", pos: "CAM", alt: ["LW"], rating: 82, club: "Flamengo" },
      { id: "14", name: "F. Pellistri", pos: "RW", alt: ["LW"], rating: 77, club: "Panathinaikos" },
      { id: "15", name: "F. Torres", pos: "LW", alt: ["RW"], rating: 76, club: "Liverpool MVD" },
      { id: "16", name: "D. Núñez", pos: "ST", alt: ["LW"], rating: 82, club: "Al-Hilal" },
      { id: "17", name: "M. Araújo", pos: "ST", alt: ["RW"], rating: 78, club: "Bragantino" },
      { id: "18", name: "B. Rodríguez", pos: "CF", alt: ["ST"], rating: 77, club: "São Paulo" },
      { id: "19", name: "M. Satriano", pos: "ST", rating: 76, club: "Lens" },
      { id: "20", name: "S. Cáceres", pos: "CB", rating: 76, club: "Atlético MG" },
      { id: "21", name: "E. Cabaco", pos: "CB", rating: 75, club: "AEK Athens" },
    ],
  },
  {
    id: "morocco", name: "Morocco", flag: "🇲🇦", group: "C",
    players: [
      { id: "1", name: "Y. Bounou", pos: "GK", rating: 84, club: "Al-Hilal" },
      { id: "2", name: "M. Hamrani", pos: "GK", rating: 75, club: "Al-Wehda" },
      { id: "3", name: "A. Hakimi", pos: "RB", alt: ["RWB", "RM"], rating: 87, club: "PSG" },
      { id: "4", name: "N. Aguerd", pos: "CB", alt: ["LB"], rating: 81, club: "Real Sociedad" },
      { id: "5", name: "R. Saïss", pos: "CB", rating: 78, peak: 82, club: "Al-Shabab" },
      { id: "6", name: "A. Masina", pos: "LB", alt: ["CB"], rating: 77, club: "Lecce" },
      { id: "7", name: "N. Mazraoui", pos: "RB", alt: ["RWB", "CM"], rating: 81, club: "Man Utd" },
      { id: "8", name: "J. El Yamiq", pos: "CB", rating: 77, club: "Valladolid" },
      { id: "9", name: "S. Amrabat", pos: "CDM", alt: ["CM"], rating: 80, club: "Fenerbahçe" },
      { id: "10", name: "A. Ounahi", pos: "CM", alt: ["CAM"], rating: 79, club: "Girona" },
      { id: "11", name: "B. El Khannouss", pos: "CAM", alt: ["CM"], rating: 80, club: "Leicester" },
      { id: "12", name: "A. Ben Seghir", pos: "CAM", alt: ["RW", "LW"], rating: 80, club: "Monaco" },
      { id: "13", name: "H. Ziyech", pos: "RW", alt: ["CAM"], rating: 79, peak: 86, club: "Al Duhail" },
      { id: "14", name: "S. Amrabat", pos: "RW", rating: 75, club: "Real Betis" },
      { id: "15", name: "S. Boufal", pos: "LW", alt: ["RW"], rating: 78, club: "Al-Rayyan" },
      { id: "16", name: "Y. En-Nesyri", pos: "ST", rating: 82, club: "Fenerbahçe" },
      { id: "17", name: "B. Dia", pos: "ST", rating: 79, club: "Lazio" },
      { id: "18", name: "A. Harit", pos: "CAM", alt: ["RW"], rating: 79, club: "Marseille" },
      { id: "19", name: "I. Ezzalzouli", pos: "LW", alt: ["RW"], rating: 79, club: "Real Betis" },
      { id: "20", name: "E. Nakkach", pos: "CM", rating: 75, club: "Antalyaspor" },
      { id: "21", name: "A. Aït-Nouri", pos: "LB", alt: ["LWB"], rating: 81, club: "Man City" },
    ],
  },
  {
    id: "australia", name: "Australia", flag: "🇦🇺", group: "C",
    players: [
      { id: "1", name: "M. Ryan", pos: "GK", rating: 78, peak: 81, club: "Roma" },
      { id: "2", name: "J. Glover", pos: "GK", rating: 74, club: "Ipswich" },
      { id: "3", name: "N. Atkinson", pos: "RB", alt: ["RWB"], rating: 74, club: "Hearts" },
      { id: "4", name: "H. Souttar", pos: "CB", rating: 79, club: "Sheffield Utd" },
      { id: "5", name: "K. Rowles", pos: "CB", rating: 76, club: "Millwall" },
      { id: "6", name: "C. Burgess", pos: "CB", rating: 74, club: "Shrewsbury" },
      { id: "7", name: "A. Behich", pos: "LB", alt: ["LWB"], rating: 74, club: "Melbourne City" },
      { id: "8", name: "L. Geria", pos: "RB", rating: 73, club: "FK Spartaks" },
      { id: "9", name: "A. Mooy", pos: "CM", alt: ["CDM"], rating: 77, peak: 80, club: "Free agent" },
      { id: "10", name: "J. Irvine", pos: "CM", alt: ["CAM"], rating: 76, club: "St. Pauli" },
      { id: "11", name: "C. Metcalfe", pos: "CM", rating: 73, club: "Western Sydney" },
      { id: "12", name: "R. McGree", pos: "CAM", alt: ["LM"], rating: 75, club: "Middlesbrough" },
      { id: "13", name: "A. Hrustic", pos: "CM", alt: ["CAM"], rating: 75, club: "Heart of Midlothian" },
      { id: "14", name: "M. Leckie", pos: "RW", alt: ["ST"], rating: 75, club: "Melbourne City" },
      { id: "15", name: "C. Goodwin", pos: "LW", alt: ["RW"], rating: 74, club: "Adelaide Utd" },
      { id: "16", name: "M. Boyle", pos: "RW", alt: ["LW"], rating: 74, club: "Hibernian" },
      { id: "17", name: "K. Taggart", pos: "ST", rating: 74, club: "Perth Glory" },
      { id: "18", name: "J. Maclaren", pos: "ST", rating: 74, club: "Melbourne City" },
      { id: "19", name: "N. Velupillay", pos: "LW", alt: ["ST"], rating: 72, club: "Melbourne Victory" },
      { id: "20", name: "C. Yengi", pos: "ST", rating: 73, club: "Ipswich" },
    ],
  },
  // ─────────────────────────── GROUP D ───────────────────────────
  {
    id: "usa", name: "USA", flag: "🇺🇸", group: "D",
    players: [
      { id: "1", name: "M. Turner", pos: "GK", rating: 78, club: "New England" },
      { id: "2", name: "P. Schulte", pos: "GK", rating: 75, club: "St. Louis City" },
      { id: "3", name: "S. Dest", pos: "RB", alt: ["RWB", "LB"], rating: 79, club: "PSV" },
      { id: "4", name: "C. Richards", pos: "CB", rating: 80, club: "Crystal Palace" },
      { id: "5", name: "T. Ream", pos: "CB", alt: ["LB"], rating: 76, peak: 79, club: "Charlotte FC" },
      { id: "6", name: "C. Carter-Vickers", pos: "CB", rating: 78, club: "Celtic" },
      { id: "7", name: "A. Robinson", pos: "LB", alt: ["LWB"], rating: 79, club: "Fulham" },
      { id: "8", name: "J. Scally", pos: "RB", alt: ["RWB"], rating: 76, club: "Gladbach" },
      { id: "9", name: "T. Adams", pos: "CDM", alt: ["CM"], rating: 80, club: "Bournemouth" },
      { id: "10", name: "W. McKennie", pos: "CM", alt: ["CDM", "RM"], rating: 81, club: "Juventus" },
      { id: "11", name: "Y. Musah", pos: "CM", alt: ["CDM"], rating: 79, club: "Atalanta" },
      { id: "12", name: "G. Reyna", pos: "CAM", alt: ["RW", "LW"], rating: 79, peak: 83, club: "Dortmund" },
      { id: "13", name: "C. Pulisic", pos: "RW", alt: ["LW", "CAM"], rating: 85, club: "AC Milan" },
      { id: "14", name: "T. Weah", pos: "RW", alt: ["RWB", "LW"], rating: 78, club: "Marseille" },
      { id: "15", name: "B. Aaronson", pos: "CAM", alt: ["RW"], rating: 76, club: "Leeds" },
      { id: "16", name: "M. Robinson", pos: "CM", rating: 75, club: "Lille" },
      { id: "17", name: "R. Tillman", pos: "CAM", alt: ["CM"], rating: 78, club: "Bayer Leverkusen" },
      { id: "18", name: "F. Balogun", pos: "ST", rating: 79, club: "Monaco" },
      { id: "19", name: "R. Pepi", pos: "ST", alt: ["CF"], rating: 79, club: "PSV" },
      { id: "20", name: "H. Wright", pos: "ST", rating: 74, club: "Coventry" },
      { id: "21", name: "C. Aaronson", pos: "LW", alt: ["RW"], rating: 73, club: "Colorado Rapids" },
      { id: "22", name: "J. Vázquez", pos: "RB", alt: ["RWB"], rating: 73, club: "Monterrey" },
    ],
  },
  {
    id: "netherlands", name: "Netherlands", flag: "🇳🇱", group: "D",
    players: [
      { id: "1", name: "B. Verbruggen", pos: "GK", rating: 82, club: "Brighton" },
      { id: "2", name: "M. Flekken", pos: "GK", rating: 79, club: "Brentford" },
      { id: "3", name: "D. Dumfries", pos: "RWB", alt: ["RB", "RM"], rating: 83, club: "Inter" },
      { id: "4", name: "V. van Dijk", pos: "CB", rating: 87, peak: 90, club: "Liverpool" },
      { id: "5", name: "M. de Ligt", pos: "CB", rating: 84, club: "Man Utd" },
      { id: "6", name: "S. de Vrij", pos: "CB", rating: 81, club: "Inter" },
      { id: "7", name: "N. Aké", pos: "LB", alt: ["CB"], rating: 82, club: "Man City" },
      { id: "8", name: "L. Geertruida", pos: "RB", alt: ["CB"], rating: 79, club: "RB Leipzig" },
      { id: "9", name: "J. Timber", pos: "RB", alt: ["CB"], rating: 82, club: "Arsenal" },
      { id: "10", name: "F. de Jong", pos: "CM", alt: ["CDM"], rating: 86, club: "Barcelona" },
      { id: "11", name: "T. Reijnders", pos: "CM", alt: ["CDM"], rating: 83, club: "Man City" },
      { id: "12", name: "R. Gravenberch", pos: "CM", alt: ["CDM"], rating: 84, club: "Liverpool" },
      { id: "13", name: "J. Veerman", pos: "CM", alt: ["CDM"], rating: 79, club: "PSV" },
      { id: "14", name: "X. Simons", pos: "CAM", alt: ["RW", "LW"], rating: 84, club: "Tottenham" },
      { id: "15", name: "C. Gakpo", pos: "LW", alt: ["ST"], rating: 84, club: "Liverpool" },
      { id: "16", name: "D. Malen", pos: "RW", alt: ["LW"], rating: 80, club: "Aston Villa" },
      { id: "17", name: "M. Frimpong", pos: "RWB", alt: ["RB", "RW"], rating: 80, club: "Liverpool" },
      { id: "18", name: "M. Depay", pos: "ST", alt: ["CF"], rating: 81, peak: 85, club: "Corinthians" },
      { id: "19", name: "W. Weghorst", pos: "ST", rating: 78, club: "Ajax" },
      { id: "20", name: "B. Brobbey", pos: "ST", rating: 78, club: "Ajax" },
      { id: "21", name: "T. Malacia", pos: "LB", alt: ["LWB"], rating: 77, club: "Man Utd" },
      { id: "22", name: "Q. Timber", pos: "CM", rating: 78, club: "Feyenoord" },
    ],
  },
  {
    id: "paraguay", name: "Paraguay", flag: "🇵🇾", group: "D",
    players: [
      { id: "1", name: "R. Fernández", pos: "GK", rating: 76, club: "Olimpia" },
      { id: "2", name: "C. Coronel", pos: "GK", rating: 75, club: "Red Bull NY" },
      { id: "3", name: "Á. Cubas", pos: "CDM", alt: ["CM"], rating: 77, club: "Vancouver" },
      { id: "4", name: "G. Gómez", pos: "CB", rating: 78, club: "Cruzeiro" },
      { id: "5", name: "F. Balbuena", pos: "CB", rating: 76, club: "Cruzeiro" },
      { id: "6", name: "O. Alderete", pos: "CB", alt: ["LB"], rating: 78, club: "Sunderland" },
      { id: "7", name: "J. Alonso", pos: "LB", alt: ["LWB"], rating: 75, club: "Atlético MG" },
      { id: "8", name: "M. Rojas", pos: "RB", alt: ["RWB"], rating: 74, club: "Cerro Porteño" },
      { id: "9", name: "M. Villasanti", pos: "CDM", alt: ["CM"], rating: 79, club: "Grêmio" },
      { id: "10", name: "A. Sanabria", pos: "ST", alt: ["CF"], rating: 78, club: "Cremonese" },
      { id: "11", name: "M. Almirón", pos: "RW", alt: ["CAM"], rating: 78, peak: 81, club: "Atlanta Utd" },
      { id: "12", name: "D. Gómez", pos: "CM", alt: ["CAM"], rating: 75, club: "Cerro Porteño" },
      { id: "13", name: "R. Sanabria", pos: "CM", rating: 74, club: "Libertad" },
      { id: "14", name: "J. Enciso", pos: "CAM", alt: ["LW", "RW"], rating: 78, club: "Ipswich" },
      { id: "15", name: "D. Gómez", pos: "RW", alt: ["LW"], rating: 75, club: "Cerro Porteño" },
      { id: "16", name: "A. Bareiro", pos: "ST", rating: 75, club: "San Lorenzo" },
      { id: "17", name: "G. Ávalos", pos: "ST", rating: 74, club: "Independiente" },
      { id: "18", name: "R. Rojas", pos: "RB", alt: ["RWB"], rating: 73, club: "Talleres" },
      { id: "19", name: "B. Ovelar", pos: "ST", rating: 73, club: "Olimpia" },
      { id: "20", name: "F. Ovelar", pos: "CAM", rating: 72, club: "Cerro Porteño" },
    ],
  },
  {
    id: "south-africa", name: "South Africa", flag: "🇿🇦", group: "D",
    players: [
      { id: "1", name: "R. Williams", pos: "GK", rating: 75, club: "Mamelodi Sundowns" },
      { id: "2", name: "R. Goss", pos: "GK", rating: 72, club: "Marumo Gallants" },
      { id: "3", name: "K. Mobbie", pos: "RB", alt: ["RWB"], rating: 73, club: "Mamelodi Sundowns" },
      { id: "4", name: "S. Mvala", pos: "CB", alt: ["CDM"], rating: 75, club: "Mamelodi Sundowns" },
      { id: "5", name: "M. Mbatha", pos: "CB", rating: 73, club: "Mamelodi Sundowns" },
      { id: "6", name: "N. Sibisi", pos: "CB", rating: 72, club: "Orlando Pirates" },
      { id: "7", name: "A. Modiba", pos: "LB", alt: ["LWB"], rating: 74, club: "Mamelodi Sundowns" },
      { id: "8", name: "T. Mokoena", pos: "CDM", alt: ["CB"], rating: 76, club: "Mamelodi Sundowns" },
      { id: "9", name: "S. Zwane", pos: "CM", alt: ["CAM"], rating: 74, club: "Mamelodi Sundowns" },
      { id: "10", name: "T. Mokoena", pos: "CM", alt: ["CDM"], rating: 75, club: "Pyramids" },
      { id: "11", name: "P. Maswanganyi", pos: "CAM", alt: ["RW"], rating: 74, club: "Orlando Pirates" },
      { id: "12", name: "T. Sithole", pos: "CM", rating: 72, club: "Royal AM" },
      { id: "13", name: "O. Mngonyama", pos: "CB", rating: 72, club: "Cape Town City" },
      { id: "14", name: "T. Zwane", pos: "RW", alt: ["LW"], rating: 73, club: "Mamelodi Sundowns" },
      { id: "15", name: "L. Mbeki", pos: "RW", alt: ["ST"], rating: 73, club: "Toulouse" },
      { id: "16", name: "M. Appollis", pos: "LW", alt: ["RW"], rating: 73, club: "Orlando Pirates" },
      { id: "17", name: "E. Rayners", pos: "ST", rating: 73, club: "Mamelodi Sundowns" },
      { id: "18", name: "I. Lepasa", pos: "ST", rating: 72, club: "Orlando Pirates" },
      { id: "19", name: "M. Foster", pos: "ST", alt: ["LW"], rating: 71, club: "Sekhukhune Utd" },
      { id: "20", name: "T. Tau", pos: "RW", alt: ["ST"], rating: 73, peak: 77, club: "Qatar SC" },
      { id: "21", name: "K. Mokoena", pos: "CM", alt: ["CDM"], rating: 72, club: "Orlando Pirates" },
    ],
  },
];
